### ISSUE TITLE
tweaking of blog main page

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#10]
The blog currently has the following tagline:

A guide to the current state of data science education

Blog Tags About RSS

Blog

Made with Hugo. Themed by Cayman. Deployed to Netlify.

- I wonder if "A roadmap to recent developments in teaching data science" might be a better tagline?
- I have no objection to the "Made with Hugo. Themed by Cayman. Deployed to Netlify." plugs.  I wonder if adding "Designed and written in California and Massachusetts." would be a complement?

**Comment by hglanz** [comment]
I agree. Changes made!

**Comment by nicholasjhorton** [comment]
This looks great.

Might you be willing to add a period after Massachusetts when you have a chance?

**Comment by hglanz** [comment]
Done!

**Comment by nicholasjhorton** [comment]
Looks great, thanks!
