### ISSUE TITLE
tweaking of blog "About" page

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#11]
This presently states:

Written in Go, Hugo is an open source static site generator available under the Apache Licence 2.0. Hugo supports TOML, YAML and JSON data file types, Markdown and HTML content files and uses shortcodes to add rich content. Other notable features are taxonomies, multilingual mode, image processing, custom output formats, HTML/CSS/JS minification and support for Sass SCSS workflows.

Hugo makes use of a variety of open source projects including:

https://github.com/russross/blackfriday
https://github.com/alecthomas/chroma
https://github.com/muesli/smartcrop
https://github.com/spf13/cobra
https://github.com/spf13/viper
Hugo is ideal for blogs, corporate websites, creative portfolios, online magazines, single page applications or even a website with thousands of pages.

Can this placeholder be replaced by much of the intro blog entry?

**Comment by hglanz** [comment]
Does this mean the intro should be here INSTEAD of a blog post? I agree that it probably makes more sense here than as a post, but then we still need an intro post....and I still think it would be good to add some more info/details to either our intro or the first blog post about the blog post itself and schedule of content releases.

**Comment by nicholasjhorton** [comment]
I would prefer to have it both places (or at least substantial overlap between the intro and the about page).  Once there are other entries, this will be less redundant.  

Please feel free to add to the entry (and let us know when you've done so): your additions sound excellent.

**Comment by hardin47** [comment]
i agree that the "about" should be just replaced with the first part of the intro (maybe without "who we are").  

i also think that we could update it as we go (e.g., if we decide we want to organize the blog entries in a particular way).  but as a placeholder, the intro material is good.

**Comment by nicholasjhorton** [comment]
My issue here is that we need to be listed as authors.  Perhaps the about page could have a link to the intro blog entry with the photos and bios?

I *really* like @hardin47's idea to update the intro entry into a roadmap of the entries as they are posted.

**Comment by hardin47** [comment]
i'm totally fine with you adding the "who we are" to the about.  

and yes, lots of things will be updated as we go along...

**Comment by hglanz** [comment]
"Who We Are" has been added, along with the google groups sign up URL/link.
