### ISSUE TITLE
Not so standard deviations

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#12]
The blog entry feels thin to me.  I wonder if @hardin47 could add some things along the lines of:

- why Hilary is so inspiring (with a shameless Pomona plug)
- why Roger has been so influential
- how their conversations have helped you see a broader data science grounded in statistics
- one or two other short anecdotes that have stuck with you

My challenge for NSSD is that it drags on at times: it would be really helpful for me to provide a bit more motivation here.

**Comment by hardin47** [comment]
Thanks for the advice!  I went a little crazy.  Hopefully it isn't too long, now.  I tried to take the perspective of:  here are examples (i wrote FIVE!) that i *directly* use in class.  but i ended up writing a lot of words, so it'll probably be good for one (both) of you to read / edit.  What do you think?

**Comment by nicholasjhorton** [comment]
Thanks!  I look forward to reviewing today.

**Comment by nicholasjhorton** [comment]
I *love* the changes.  See https://github.com/hglanz/DS-Blog-Ex/commit/4bbbe735345e7b373aa1cb43fbb8a2e605d53adb#diff-f6b04de319e95961e01b1d1b4a124ad9 for my light edits.  Please ignore or incorporate as you see fit (I'm sorry that the latter is the default and the former requires work on your part.

Since you have one more crack at approving this within the week issue, I'm closing this now.
