### ISSUE TITLE
R markdown entry

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#13]
I'd be glad to assist @hglanz with this entry.

I'd suggest citing: https://escholarship.org/uc/item/90b2f5xh

and https://rmarkdown.rstudio.com

as well as linking back to the NASEM report entry.

Please let me know if I can help.

**Comment by hglanz** [comment]
Draft pushed to the repo and the staging site. Please take a look and let me know what you think @nicholasjhorton  @hardin47 . Thanks!

**Comment by nicholasjhorton** [comment]
This looks great.  I made some changes: can you please review https://github.com/hglanz/DS-Blog-Ex/commit/e4e17b332f4a6cdfc17c10a8b2c2ba0a7165a664

**Comment by hardin47** [comment]
i made a few changes, too.  I'm good to go on this entry!  I'll let @hglanz close the issue, though.

**Comment by hglanz** [comment]
Looks great! Thanks so much! I'll be sure to minimize the number of exclamation marks in my future posts :)
