### ISSUE TITLE
ingesting data entry

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#14]
I spoke with @hardin47 about this entry: the plan is for her to plug the importance of data ingestation in the data science analysis cycle (as mentioned in the NASEM entry) then riff on one of the examples from https://arxiv.org/abs/1603.04912

I'm glad to assist to help finalize this once she has stubbed or outlined the entry.

**Comment by hardin47** [comment]
i wrote a (complete) draft.  would love to have feedback from @nicholasjhorton and @hglanz !

**Comment by hglanz** [comment]
@hardin47 It looks great! Have you heard of datapasta? It might be a good addition to your list of "R packages for ingesting data"....probably at the top. Check it out here if you haven't seen it:

https://github.com/MilesMcBain/datapasta

**Comment by nicholasjhorton** [comment]
I pushed some (minor) changes and comments: can you please review https://github.com/hglanz/DS-Blog-Ex/commit/e4e17b332f4a6cdfc17c10a8b2c2ba0a7165a664 and let me know if you see any issues?

**Comment by hardin47** [comment]
great, thanks to you both!  i've pushed a few minor things.  i'm closing this comment, ingesting data blog is done.

one small thing is that i've linked to https://teachdatascience.com/nasem/

i hope we can change the file/folder for the first blog?  the url including the date seems unwieldy...
