### ISSUE TITLE
rstudio projects

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#15]
@nicholasjhorton has agreed to flesh out the entry:

- add motivation for RStudio
- add motivation for projects (as part of workflow)
- link to prior discussions of projects from RStudio/tidyverse folks

**Comment by nicholasjhorton** [comment]
I'm hoping to complete this by the end of the day today (to allow @hardin47 and @hglanz to review)

**Comment by hglanz** [comment]
The post looks good, except the lack of text between "Why Use Projects?" and the subsection "Keeping track of data" is a little awkward. It would be better to have a little overview text at the start of the "Why Use Projects?" section or just eliminate it and use the current subsection titles as sections. Thoughts?

**Comment by nicholasjhorton** [comment]
Still haven't gotten to this: I hope to do so today.

**Comment by nicholasjhorton** [comment]
I've pushed my changes (see https://github.com/hglanz/DS-Blog-Ex/commit/b8cec6db3e664f930e95f33749075d0659c9b864 for the diffs).  This is now ready for @hardin47 to review then close the issue.

**Comment by hardin47** [comment]
looks great!
