### ISSUE TITLE
tagging plan

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#17]
I'd be glad to take a lead on this once we have the first set of blog entries fleshed out.

**Comment by hardin47** [comment]
how much of a pain is it to change "plot" to "visualization" ?

**Comment by hglanz** [comment]
Change it where? Or do you just mean in our tags? It shouldn't be hard at all...

**Comment by hardin47** [comment]
i just mean in the tags.  i was looking at the tags, and it says that there are 18 "plot" tags.  I was thinking visualization would be better.  but maybe "plot" means something else?

**Comment by hglanz** [comment]
I'm in favor of "visualization". You have "plot" in many of your posts, @nicholasjhorton . What are your thoughts here?

**Comment by nicholasjhorton** [comment]
I made some light edits in the published repo (see https://github.com/hglanz/teachdatascience_blog/commit/27cb256787d6ad372e2d0bd1e1da4b960104156c)

**Comment by hardin47** [comment]
seems like we have #report and #reports ...

**Comment by nicholasjhorton** [comment]
I have no preference.  Probably my bad here.  It will be easier once our set of tags are more fleshed out on the published site.  

If you can fix that would be fab.

Thanks in advance,

Nick


On Jun 6, 2019, at 10:36 AM, Jo Hardin <notifications@github.com> wrote:

seems like we have #report and #reports ...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


Nicholas Horton 
Beitzel Professor of Technology and Society (Statistics and Data Science)
Amherst College

**Comment by nicholasjhorton** [comment]
I made both "reports".
