### ISSUE TITLE
diversity in data science entry

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#19]
#Data4BlackLives, #WiML2018, @black_in_ai, @_LXAI, @InclusionInML, @RLadiesGlobal, #statfest

**Comment by hardin47** [comment]
I just posted a draft.  I had a lot of trouble *starting* the blog, so I'd appreciate any feedback (feel free to edit away). Thanks @nicholasjhorton @hglanz !

**Comment by nicholasjhorton** [comment]
I like the way that this is coming together.  I see your issues with the opening.  Can you build from the NASEM report:

ENSURING BROAD PARTICIPATION
According to the South Big Data Innovation Hub’s Keeping Data Science Broad, “the variety of perspectives such diversity [in terms of race, gender, religious affiliation, socioeconomic status, ethnicity, and first-generation status] provides is as essential as that provided by the transdisciplinary nature of data science for innovation and growth of the field” (Rawlings-Goss, 2018, p. 29). The report explains that the first step in creating a more inclusive environment is to ensure that students and faculty alike—at all types of educational institutions—have equitable access to resources (e.g., high-quality data, tools, technology, adaptable and appropriate curriculum, and advisors). Also crucial to retaining broad participation in data science were a “culturally relevant curriculum,” a more diverse faculty, and collaborations between majority-serving and minority-serving institutions (Rawlings-Goss, 2018, p. 31).

Thus, it is the responsibility of academic institutions to ensure inclusion and broad participation and engagement in data science programs. Master (2017) suggests that data science programs at higher education institutions increase exposure to data science fields, broaden beliefs about who belongs in these fields, challenge students’ beliefs about fixed abilities, and show that data science can make a difference in society in order to broaden participation and engagement in data science. Williams (2017) suggests that faculty adjust curriculum to be more inclusive, create opportunities for students to engage in community data, affirm student ability, and create diverse teams of students. The efforts highlighted by Master and Williams not only lead to increased engagement, but they also stand to sustain participation of underrepresented populations in data science. If data science is to avoid a similar decrease in participation that occurred in the 1980s in computer science among female students, it is imperative that underrepresented students are supported both academically and through mentorship, recognizing the opportunities that the field of data science presents and the value they can add to it.

Some of the introductory data science courses described in this report have made inclusion and broad participation a central goal, shaping pedagogy, technical infrastructure, and staffing. Some notable steps include the following:


which in turn builds from the (still hard to Google) "Keep Data Science Broad" report?  http://bit.ly/KeepingDataScienceBroad_Report



I suspect that if there was ever a blog entry that could benefit from some external vettting, this is one I'd nominate.  For example, they would always use "historically underrepresented" in their descriptions.  

I think that the tone we want is respectful and inclusive.  

I fixed some minor typos while I was at it.

**Comment by hardin47** [comment]
Great suggestions, and I especially like the suggestion to vet it.  I can ask Emma Benn, Miles, Renee, and a few R Ladies to look it over.    I'll cc you all (tonight or tomorrow) after I make changes and then send it out.  Thanks!

**Comment by hardin47** [comment]
I posted a revision and also sent the link to a few people.  Feel free to look at it. Hopefully I'll get more feedback soon to incorporate.  Thanks!

**Comment by hardin47** [comment]
i heard back from a few people and added in their ideas into the diversity blog.  haven't heard from any of the r ladies i asked, but i think the blog is ready for a final review by @nicholasjhorton @hglanz .  Thanks!

**Comment by nicholasjhorton** [comment]
This looks great.  See minor tweaks via https://github.com/hglanz/DS-Blog-Ex/commit/fa01baa68494c4a6aa894f10ff0c3f308bb3b83d

**Comment by hglanz** [comment]
Looks great! I'm checking the box now.
