### ISSUE TITLE
linking blogs

### ISSUE THREAD

**Issue by hardin47** [hglanz/DS-Blog-Ex#21]
I've noticed that we are going to need to link quite a few of the blogs (to each other).  What is the best mechanism for doing that?

**Comment by nicholasjhorton** [comment]
Hard to tell until we have some blogs posted. Let’s defer until next week. 

All the best,

Nick

**Comment by nicholasjhorton** [comment]
https://teachdatascience.com/XX seems to work (thanks to @hglanz's efforts!)  I added a few such links to the NASEM entry from ingesting data and rmarkdown.
