### ISSUE TITLE
draft roundtable entry

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#26]

**Comment by nicholasjhorton** [comment]
Ready for review: https://github.com/hglanz/DS-Blog-Ex/blob/master/content/post/2019_06_10_Roundtable/dsert.Rmd

**Comment by hardin47** [comment]
seems generally good.  two (potentially related) problems:  

1. image is messed up
2. file name is messed up

**Comment by nicholasjhorton** [comment]
@hglanz I'm puzzled by this: any idea what I did wrong?

**Comment by hglanz** [comment]
Yes, I've fixed it now. You had to put the image inside /static/post/dsert/ as well.
