### ISSUE TITLE
draft intro to github entry

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#27]
focus on why, setting up github username, web interface

**Comment by nicholasjhorton** [comment]
I'm assuming that the entries will be titled github1, github2, and github3.

**Comment by hglanz** [comment]
Naming convention implied by @hardin47 's post: github, githubR, gitclass.

I like this.

**Comment by nicholasjhorton** [comment]
I've pushed my first draft of the Intro to Github entry: comments and suggestions welcomed from @hglanz and @hardin47

**Comment by hardin47** [comment]
nice job!  i made some pretty minor changes here https://github.com/hglanz/DS-Blog-Ex/commit/3a2aeabed75c52f9a86a1c3e692e8ef3a795641a.  I pushed but didn't rebuild.
