### ISSUE TITLE
draft github for R

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#29]
builds on intro to github with focus on RStudio interface and pedagogy

**Comment by hardin47** [comment]
@hglanz 

you might want to link to this:  https://www2.stat.duke.edu/~mt324/presentations/posters/uscots-poster-2019.pdf

or maybe not ... seems like there are lots of people presenting on using GitHub with R?

**Comment by hardin47** [comment]
also these resources are good:


* Jenny Bryan's package `usethis` "facilitates interactive workflows for R project creation and development."  https://www.tidyverse.org/articles/2019/04/usethis-1.5.0/

* Emily Riederer's streamlined process for interfacing R Projects and GitHub https://emilyriederer.github.io/projmgr/, and associated blog about the work: https://emilyriederer.netlify.com/post/rmarkdown-driven-development/ .

**Comment by hardin47** [comment]
also, i think at the very beginning of this process, i sort of started this blog.  just sending you the link in case you find it helpful.  please don't feel free to use this, but if you don't use it, maybe we should delete the folder / files associated with the old blog entry.

https://pensive-bartik-e3e658.netlify.com/projectsgit/

**Comment by hglanz** [comment]
@hardin47 your projectsgit was a great start! So, I left you on as an author and a lot of what you'd already written. I drafted some more without having looked at the other GitHub entries, but definitely stopped short.

@nicholasjhorton mentioned focusing on pedagogy in this post, but I didn't want to "steal" anything from the GitHub Classroom post. So, I'll take suggestions on how to proceed but keep mulling it over myself as well. 

It looks like @hardin47 referred to this post as githubR and @nicholasjhorton 's post as just github.....and then her own post as gitclass. I like this naming scheme and will update mine accordingly in my next commit.

**Comment by nicholasjhorton** [comment]
Should we do a (part 1 of 3), (part 2 of 3), etc. for the titles?  I'm good either doing this for all or doing it for none of them.  
![Screen Shot 2019-06-06 at 8 55 44 AM](https://user-images.githubusercontent.com/530542/59034409-fdda5080-8838-11e9-91c6-4c5f128c7798.png)

**Comment by nicholasjhorton** [comment]
PS this entry looks great to me: I had no suggestions (besides adding "workflow" into the tags, which I've done).

**Comment by hardin47** [comment]
i'm good with this post!  i just checked it off.  

i guess i wouldn't use part1, part2, part 3.  they sort of build on each other, but i think i prefer having people focus on the more specific topic (e.g., within R or GitHub Classroom)

**Comment by nicholasjhorton** [comment]
I removed the (part 1) from my entry.

**Comment by nicholasjhorton** [comment]
I've reopened this issue: I think that it would be helpful to note that *not* all operations can be done within the RStudio interface.  (As one example, "git stash" needs to be run from the shell.). Would some mention of this be appropriate?

**Comment by hglanz** [comment]
I added a line in about this and updated the staging site. I'm checking the other entries off now and I just updated the live site with the roundtable entry
