### ISSUE TITLE
draft screencast entry

### ISSUE THREAD

**Issue by hardin47** [hglanz/DS-Blog-Ex#30]
@nicholasjhorton 

way back when we were still using email to communicate, we had a discussion about changing the title of the screencast blog ...

> while I like the idea of the title, I think the actual title should be more descriptive.  Something like “What is the tidyverse?: watching an expert at work”   or “Watching an expert think through the tidyverse process”  

any thoughts on making that change?

**Comment by nicholasjhorton** [comment]
How about "Watching an expert work through a data analysis" or

"Watching an expert work through a data analysis using the tidyverse"?

**Comment by hardin47** [comment]
I like the second one.  Thanks!

Jo Hardin
Pomona College
jo.hardin@Pomona.edu<mailto:jo.hardin@Pomona.edu>

On Jun 1, 2019, at 4:41 PM, Nicholas Horton <notifications@github.com<mailto:notifications@github.com>> wrote:


How about "Watching an expert work through a data analysis" or

"Watching an expert work through a data analysis using the tidyverse"?

**Comment by nicholasjhorton** [comment]
I've committed the changes: @hglanz this is all set to copy to the real site.
