### ISSUE TITLE
one kind of technical one about scraping GitHub profile pages to count student commits

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#31]
@nicholasjhorton to work with Amelia to draft this

**Comment by nicholasjhorton** [comment]
Amelia agreed: Nick to follow up.

**Comment by nicholasjhorton** [comment]
I zoomed with Amelia yesterday: she will work to get a revised draft for a guest entry (not jointly published) next week.

**Comment by nicholasjhorton** [comment]
I've added Amelia's draft.  @hglanz can you please rebuild the staging site when you have a chance?  I believe that I've added the one image into the correct place in static/post.  Thanks in advance, Nick

**Comment by hardin47** [comment]
@nicholasjhorton can you add `purrr::` in all the places where `purrr` commands are used?  i find the package connection to be incredibly helpful, and i think the connection to `purrr` could be particularly useful given how much amelia talks about implementing `purrr` ideas.

also, a *very* small point...  the following sentence is missing a word:

>  If you were authenticating with site other than GitHub, this code would need to be different,

I think it should be:

>  If you were authenticating with a website other than GitHub, this code would need to be different,

**Comment by nicholasjhorton** [comment]
Done (on both counts).
