### ISSUE TITLE
explore alternative organization of the home page

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#32]
short excerpt from current entries, sidebar with listing?

goal: straightforward to implement and maintain

**Comment by hglanz** [comment]
Lots of options, but I went through the entire page of Huge templates that I linked to you previously. Take a look and let me know which one(s) you'd like to try out on the staging site:

https://themes.gohugo.io/hugo-theme-learn/
https://themes.gohugo.io/hugo-theme-techdoc/
https://themes.gohugo.io/hyde/
https://themes.gohugo.io/blackburn/
https://themes.gohugo.io/hyde-y/
https://themes.gohugo.io/hugo-h5bp/
https://themes.gohugo.io/hugo-theme-techlog-simple/
https://themes.gohugo.io/hugo-bootstrap-premium/
https://themes.gohugo.io/midnight/
https://themes.gohugo.io/hugo-phlat-theme/

I think I like the latter ones more... Look forward to hearing from you @nicholasjhorton and @hardin47

**Comment by hardin47** [comment]
My favorite is

https://themes.gohugo.io/hugo-bootstrap-premium/

But does the list of blogs come up on the side-bar?  I like the list being on the sidebar for all the screens (or especially for the home screen).

**Comment by nicholasjhorton** [comment]
I like that one as well.  

Nick


On Jun 6, 2019, at 10:07 AM, Jo Hardin <notifications@github.com> wrote:

My favorite is

https://themes.gohugo.io/hugo-bootstrap-premium/

But does the list of blogs come up on the side-bar? I like the list being on the sidebar for all the screens (or especially for the home screen).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


Nicholas Horton 
Beitzel Professor of Technology and Society (Statistics and Data Science)
Amherst College

**Comment by hglanz** [comment]
How do you like dem apples?

https://dazzling-lichterman-6802d7.netlify.com/

Phew, that was a bit of work because I know so little about websites....haha. I think it's in good shape though. 

I'm not changing the staging site, but I wanted to use a test site other than the staging site so I wasn't messing with anything we had in place. @nicholasjhorton and @hardin47 just give me the green light to transition the staging and live site over to the new theme and I will.

And/or let me know if you have any comments or questions. 

For example, this new theme includes author on the post. I like how we've been posting "anonymously" so far, which just means removing the author field from the .Rmd file for the post. I think this is alright because we have a record of authorship on our wiki, but let me know if you want to go another direction.

Thanks!

**Comment by hglanz** [comment]
Also, full disclosure....I don't know what will happen to existing comments when the transition is made. We should be able to test on the staging site, but I'm not seeing some of our older comments already.....?

**Comment by hardin47** [comment]
I LOVE IT!!!!  YAY!!!! You are amazing.  tbh, i actually like the idea of knowing authorship.  i don't have strong feelings, and it just seemed to work to be anonymous previously, but it doesn't seem like a terrible idea for us to each own our words.  either way, fine with me to take the names off the .Rmd files if you all prefer to be anonymous.

the comments thing kind of sucks.  but i think the transition to the other format is worth losing the comments.  we could also reach out to individuals with apologies.  or we could copy and paste the comments.  if you think it makes sense to copy and paste, i'd take on that task.  (that is, i'll just copy all the previous posts to a text file and re-comment them after the new format.)

**Comment by nicholasjhorton** [comment]
I love it as well. Thanks for your work!

I’m fine with hiding or displaying authorship. 

Can you backup the current deployed site and make the switch?  I’m not too concerned about losing the comments. 

All the best,

Nick

**Comment by hglanz** [comment]
I will certainly back everything up first. I'll make the switch on both sites tonight when I post the blog entry for tomorrow.

@hardin47 could you copy the comments by midnight tonight or is that too tight a timeline? I'm happy to just screenshot the pages as a first effort. I will go ahead and display authorship then.

**Comment by hardin47** [comment]
i should be able to copy comments tonight after dinner.  i'll let you know when i do so.  if i haven't said anything, please feel free to ping me!

**Comment by hardin47** [comment]
i copied all of the comments from V1 of the blog into a word doc that i pushed onto our staging github site.

as i was going through them, i realized that the vast majority of the comments are from david kane and are not particularly helpful.  that said, he does write a handful of thoughtful things, and he's probably going to be really annoyed if his comments all disappear.  for example, did you all notice that he wrote this:  https://www.davidkane.info/post/2019-06-21-pair-programming/

i mean, we should probably think of some creative way to be kind, but i don't really think we need all of the comments to get posted back to the new version.

**Comment by nicholasjhorton** [comment]
David’s pair programming post is quite thoughtful. I share his concern about student’s inclination to divide and conquer. 

All the best,

Nick

**Comment by hglanz** [comment]
Thanks so much @hardin47 ! I think Nick and I agree with you about David. I'll email again tonight, as usual, when the new post is up. 

The backups of our two sites will be local to me, so the next time you two pull it will likely be the new sites.

**Comment by hardin47** [comment]
i'm in the middle of a few edits to shiny2.  can i push in about 15 minutes?  or should i wait?  i was also planning to give CODAP feedback, should i wait or push those edits, too?

**Comment by hardin47** [comment]
ok, i'm done with editing for tonight.  as soon as the new format goes up i'll be sure to email different groups to re-announce the blog.  thanks!!

**Comment by hardin47** [comment]
looks great!  nice work.

one small question:  is there a way to change the default number of posts on a "page".  right now it looks like there are 5. i'd suggest 10.

similarly, in the sidebar, 10 blogs are listed.  i'd suggest 15 or 20.

what do you think?

**Comment by hardin47** [comment]
also, interestingly, the URLs for the staging site got changed to include the date.  

https://pensive-bartik-e3e658.netlify.com/2018/07/09/codap/

i'm not sure it matters very much, but it is something to be aware of.

**Comment by nicholasjhorton** [comment]
Kudos to @hglanz for his work!

**Comment by hglanz** [comment]
The staging site links have been reverted to the original style too now :)
