### ISSUE TITLE
draft of shiny blogs

### ISSUE THREAD

**Issue by hardin47** [hglanz/DS-Blog-Ex#33]
saw this recent JSE article.  maybe for "learn more"?

https://amstat.tandfonline.com/doi/full/10.1080/10691898.2018.1436999#.XPgaJNNKj_8

**Comment by nicholasjhorton** [comment]
I like how https://pensive-bartik-e3e658.netlify.com/shiny1/ is shaping.

I wonder if it's feasible to begin with a brief motivation for the importance of dynamic visualizations in the workforce.

Then perhaps a discussion of how Shiny can be used be instructors:

- way to bring in demonstrations led by the instructor
- way for students to work on activities created by the instructor

Or in higher level courses

- students create simple Shiny apps
- students augment a moderately complicated Shiny app and add to it (I have an example of how I did this for an explorer of the NYC Restaurant Violations data)

**Comment by hglanz** [comment]
Thanks @nicholasjhorton . Perhaps I forgot how we wanted to approach the two-day shiny entry. I thought this first one could be the introduction that you see and the second would be the more pedagogically-focused one.....so I've put most of your comments in the second post for now.

I'm happy to put some motivation in the first entry that alludes to the second. Is this what you suggest?

Everything is pushed and live on the staging site now. If you have a link and stuff I can add for your shiny augment example that would be great. I just have my two student projects in there right now.

**Comment by hardin47** [comment]
shiny1, minor edits here: https://github.com/hglanz/DS-Blog-Ex/commit/af49159ee3ff511a2227596ef214efc0b9e677d4

* i like the breakdown of what is shiny first and teaching second.

* i like the fact that you used examples where one is straightforward and available right there and the other is on github.  but i'd recommend expanding the screen shots.  
    * for both of them, i'd include "get code" in the screen shot.  
    * and for the iris data, i'd include the screen shot of server.R and ui.R below.

* what do you think about `shiny` instead of Shiny?  i don't have strong feelings, but everywhere else in the blog we use ticks to describe packages and functions.

* I would love to see a little bit of reflection on where a Shiny app lives.  That is, pointing out to the user that the app takes over R and lives locally unless it is shared.  It can be shared via a Shiny server hosted by, for example, your university  or by RStudio.

**Comment by hardin47** [comment]
shiny2, minor edits here: https://github.com/hglanz/DS-Blog-Ex/commit/1d2de3ee79af650cdd5afac06b1574d080fd2160

* does `learnr` use the Shiny platform?  if not, then i'd probably leave out that sentence.  if so, how?

* the classification app is missing a URL for where the app is hosted:

> The Classification app was also created by a team of three students as a final project, and they chose to build a tool for exploring different classification methods. The app can be found here().

* maybe because i can't actually play with the app, but i don't really understand how the choice of dataset is so powerful here:

> The app is fun for its simultaneous simplicity and complexity. The classification methods included are somewhat advanced and nice to visualize.  However, the coup de grace is the choice of datasets which provides stunning clarity to how the different methods handle different data situations.

**Comment by nicholasjhorton** [comment]
Here are my minor comments on shiny1 (which otherwise looks great): https://github.com/hglanz/DS-Blog-Ex/commit/10a942765e531d660fe228002b9467e07560f56f

**Comment by nicholasjhorton** [comment]
shiny 2 looks good: I made some trivial tag changes.  Once @hardin47's questions are addressed I'm ready for you to post both entries.
