### ISSUE TITLE
draft of leaflet

### ISSUE THREAD

**Issue by hardin47** [hglanz/DS-Blog-Ex#34]
@nicholasjhorton : i just looked at the leaflet blog, and i have a few comments:

* the leaflet blog seems to have a july date.  that can't be right, is it?

* i made some edits here (https://github.com/hglanz/DS-Blog-Ex/commit/76d1dbffddbca41912deb93c49bd7d5246e1da67), but i didn't rebuild.

**Comment by nicholasjhorton** [comment]
I fixed the date and thanked @hardin47 for her edits!

**Comment by nicholasjhorton** [comment]
I added a pointer to the leaflet cheatsheet: https://github.com/hglanz/DS-Blog-Ex/commit/02bf1eb86031085a296670d57edc6cb04e112cc8
