### ISSUE TITLE
infer

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#38]

**Comment by hardin47** [comment]
`infer` blog is up!  ready for comments from @hglanz and @nicholasjhorton .  I also sent the link to Andrew and Chester.  Hope they can give me some good feedback.

**Comment by nicholasjhorton** [comment]
Here's my question about infer: is this just a tool for tidy bivariate comparisons?  How does that work in a multivariate world?  Can you add a second example where infer is used within a multiple regression framework?  Or is this an inherent limitation?

**Comment by hardin47** [comment]
the point of `infer` is to understand the creation of a sampling distribution (under some model, likely the null model).  it could easily take in a global F statistic (e.g., for a multivariate linear model), but i don't think that code is written.  

i don't see this as a shortcoming.  i don't really want to do multivariate modeling using `infer`.  in fact, maybe i don't even want to use inference at all when i'm doing multivariate modeling.  

but i do want my students to understand what a sampling distribution is.  and indeed, for them to be well enough versed in the idea of a sampling distribution that they can conceptualize the idea in a multivariate linear model:  ok, if i set this ONE beta-coefficient to zero and simulated from some data structure, i could get a t-like sampling distribution from the b-coefficients i get for each simulation.  and then i could compare my observed b-coefficient to that histogram.  OH!  THAT'S WHERE the p-value comes from when i look at the linear model output.

**Comment by nicholasjhorton** [comment]
On Jun 9, 2019, at 10:26 AM, Jo Hardin <notifications@github.com> wrote:

the point of infer is to understand the creation of a sampling distribution (under some model, likely the null model). it could easily take in a global F statistic (e.g., for a multivariate linear model), but i don't think that code is written.

MY RESPONSE: Stating this goal ("to understand the creation of a sampling distribution (under some model, likely the null model)") explicitly would help address my concern.  Let's not mention the code that's not there.  

i don't see this as a shortcoming. i don't really want to do multivariate modeling using infer. in fact, maybe i don't even want to use inference at all when i'm doing multivariate modeling.

MY RESPONSE: I'm not so wild about "don't even want to use inference when doing multivariate modeling.  I'm sure that's not what you really mean.  Or you've been brainwashed by the bivariate statistics police.  :-<

but i do want my students to understand what a sampling distribution is. and indeed, for them to be well enough versed in the idea of a sampling distribution that they can conceptualize the idea in a multivariate linear model: ok, if i set this ONE beta-coefficient to zero and simulated from some data structure, i could get a t-like sampling distribution from the b-coefficients i get for each simulation. and then i could compare my observed b-coefficient to that histogram. OH! THAT'S WHERE the p-value comes from when i look at the linear model output.

MY RESPONSE: I'm on board with this goal.  Perhaps you could motivate it through something like A/B testing and add some throwaway line that this background will help students grok sampling distributions, inference, and p-values when they move beyond two sample comparisons to multiple regression?

My concern is that this the first (and only?) entry of the summer that mentions p-values.  So I'd like to ensure that it's grounded appropriately.

**Comment by hardin47** [comment]
@nicholasjhorton - Thanks for the really great feedback!  I've updated the `infer` entry.  https://github.com/hglanz/DS-Blog-Ex/commit/8f8a5dcab49c8a5bbc7c8a23878e7db5305ae4a5  Let me know what you think.  Specific comments below.

YOU SAID:  Let's not mention the code that's not there.

MY RESPONSE: I'm not sure to what you are referring.  Did I do that?

YOU SAID: I'm sure that's not what you really mean.  Or you've been brainwashed by the bivariate statistics police.  :-<

MY RESPONSE:  what i mean is that i don't think that forward stepwise selection with nested F-tests is the only way to go.  for so many reasons.  that it's better to think about context and/or cross validated models.  [n.b. this was just a throw away comment related to how i think about statistical modeling, it wasn't meant to be related to the `infer` blog.]

YOU SAID: "I'm on board with this goal.  Perhaps you could motivate it through..."

MY RESPONSE:  I tried.  I don't think you were suggesting that I change the entire example (which I didn't do).  What do you think about the motivation now?

**Comment by nicholasjhorton** [comment]
On Jun 10, 2019, at 5:26 PM, Jo Hardin <notifications@github.com> wrote:

@nicholasjhorton - Thanks for the really great feedback! I've updated the infer entry. 8f8a5dc Let me know what you think. Specific comments below.

YOU SAID: Let's not mention the code that's not there.

MY RESPONSE: I'm not sure to what you are referring. Did I do that?

NICK'S SECOND RESPONSE: I meant mentioning vaporware code in infer that hasn't been written.

YOU SAID: I'm sure that's not what you really mean. Or you've been brainwashed by the bivariate statistics police. :-<

MY RESPONSE: what i mean is that i don't think that forward stepwise selection with nested F-tests is the only way to go. for so many reasons. that it's better to think about context and/or cross validated models. [n.b. this was just a throw away comment related to how i think about statistical modeling, it wasn't meant to be related to the infer blog.]

NICK'S SECOND RESPONSE: I don't believe in forward stepwise selection either, unless you promise to ignore the p-values.  I'm thinking much more about a simpler situation with X, Y, and possiible confounder Z.

YOU SAID: "I'm on board with this goal. Perhaps you could motivate it through..."

MY RESPONSE: I tried. I don't think you were suggesting that I change the entire example (which I didn't do). What do you think about the motivation now?

NICK'S SECOND RESPONSE: I like it much better.  Thanks for the excellent revisions!
