### ISSUE TITLE
mosaic entry

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#39]

**Comment by nicholasjhorton** [comment]
I've drafted this: comments and suggestions welcomed by @hardin47 and @hglanz.  I also worry that I'm missing a step in getting the graphs to display.

**Comment by hardin47** [comment]
Great entry.  I love the `mosaic` examples as well as the contrast to base R and `dplyr`.  Edits here:  https://github.com/hglanz/DS-Blog-Ex/commit/6c4f98b8bca04f4fd95c3696c6e01f835ecb314b


One question:
* I think that we should be explicit about the fact that the mosaic package augments functions.  either by using `mosaic::mean(...)`  or by using text:  "If only the means are needed, they can be calculated instead, using the `mosaic` augmented version of `mean`."   @nicholasjhorton , which do you prefer?

**Comment by nicholasjhorton** [comment]
Addressed the concerns from Jo: https://github.com/hglanz/DS-Blog-Ex/commit/8de59db451ea9fcd19b5cb8a68b961b0db946763

**Comment by hardin47** [comment]
@nicholasjhorton  wrote:   (for example, the base::mean() function has augmented functionality related to formulas and the data= option).

Is that really what you meant?  Or did you mean:

 (for example, the base::mean() function is augmented to include formulas and the data= option).

Or maybe even better:

 (for example, the mosaic::mean() function has augmented functionality related to formulas and the data= option).

**Comment by nicholasjhorton** [comment]
I implemented your second suggestion: thanks for the careful read!

**Comment by nicholasjhorton** [comment]
Added two additional points to mosaic entry: https://github.com/hglanz/DS-Blog-Ex/commit/e764d9b64b9e9aa53dca3ed4ae321da7da492ef0

would welcome another set of eyes on these as it is scheduled to go live tomorrow.  Thanks in advance, Nick

**Comment by hardin47** [comment]
the phrasing isn't necessarily wrong, per se, but this seems a little awkward:  `If R were reimplemented functions such as...`

i don't know what R being "reimplemented" means.    and i'm not sure what the correct grammar is, but the reading of it seems to necessitate a comma:  `If R were reimplemented, functions such as...`

thoughts?

**Comment by nicholasjhorton** [comment]
If R was rewritten from scratch?

Might you be willing to make the change that you find acceptable?  I’m not going to be in front on my computer for several hours. 

Thanks in advance if that’s feasible. 

All the best,

Nick

**Comment by hardin47** [comment]
ok, done.  @hglanz i think the mosaic entry is good to go for tomorrow.  (I pushed but i didn't rebuild... that's okay, right?)

**Comment by hglanz** [comment]
Yes, that's fine. Updating live site now...
