### ISSUE TITLE
outreach to Statistics Bloggers, RBloggers, other places

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#4]

**Comment by nicholasjhorton** [comment]
I requested that we be added to stats bloggers.

For r bloggers there is the following requirement:

I linked to r-bloggers.com from my blog's blogroll? *
Bloggers who wish to join should *first* give a blogroll link to https://www.r-bloggers.com. Blog's without a linkback will not be added to the site (this is checked before a feed is added - so please make sure this is o.k.). R-bloggers offer you a link-back from it's blogroll (at random) and from the contributors page, on top of the linkback within your posts on the site (p.s.: it is even better to add to your sidebar the titles of the r-bloggers feed: http://feeds.feedburner.com/RBloggers )

@hglanz might you be willing to investigate whether this is feasible?

**Comment by hglanz** [comment]
I'll look into this.....are we all for it if it is possible?

**Comment by nicholasjhorton** [comment]
I think that r-bloggers would be a *great* outlet.  (We may need to set up an R tag.)

On May 30, 2019, at 3:16 AM, Hunter Glanz <notifications@github.com> wrote:

I'll look into this.....are we all for it if it is possible?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or mute the thread.


Nicholas Horton 
Beitzel Professor of Technology and Society (Statistics and Data Science)
Amherst College

**Comment by hglanz** [comment]
I also think R-bloggers would be a great outlet, but we talk about more than just R in our blog....and some form of this seems to be a requirement to be included in theirs: https://www.r-bloggers.com/add-your-blog/

**Comment by nicholasjhorton** [comment]
Can we set up an R tag as described in that link?  (Note that I added some R verbiage to early posts to help make things more R-centric.)

THEY WRITE:

What to do if I also write about other things besides R?

There is a solution.

All you need to do is add a category (or a tag) named “R” (or r-project, or whatever is comfortable for you), use it for all your R related posts, and submit it instead.
To most modern blogging platform (WordPress, blogger, movable type, etc…), there is a way for getting the RSS feed of a particular category only (you can submit just the category link, and I’ll find the RSS feed link.)

**Comment by hglanz** [comment]
We can definitely do this....I had just noticed that we didn't have an R tag as of yet. @nicholasjhorton did you go back and add it to certain posts? We should do this...

**Comment by nicholasjhorton** [comment]
I've been adding a category for R and notR: adding an R tag would be easy to accomplish.
