### ISSUE TITLE
5 quick tips

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#40]
@hglanz to work with Kelly Bodwin

**Comment by nicholasjhorton** [comment]
I really like this.  I'm appreciative and quite pleased. 

My main comment is that I'd like this to have posted after the R Style Guide post.  Can we shuffle the schedule?

Another minor issue: while I suggest "quick" the entry is long so perhaps we should remove the word.

**Comment by nicholasjhorton** [comment]
This really is fabulous!  

I've added a second ref to the Rstyle entry and made some other edits.  Can @hglanz  please review and then share with Kelly along with the updated publication plan?

**Comment by hglanz** [comment]
So you both have made edits? I will review and pass along to Kelly. I like @nicholasjhorton 's new proposed publication plan and will share with Kelly. I agree that she did a great job and that it fits better after certain other posts.

Your edits have helped as well!
