### ISSUE TITLE
pair programming

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#41]

**Comment by nicholasjhorton** [comment]
I've drafted this: comments and suggestions welcomed by @hardin47 and @hglanz

**Comment by hardin47** [comment]
LOVE the image.  Yay!!!  Very minor edits here:  https://github.com/hglanz/DS-Blog-Ex/commit/6aeef3f798d288c547bed7aba7b4eac249f31d14

Meanwhile, what do you think about adding some **ideas** for paired programming in data science.

* Working through a new package vignette where one person is reading and explaining and the other is coding.
* Different responsibility for an analysis:  one person codes, one person documents.  I'm thinking something like:

Person A codes the appropriate t-test
Person B annotates to include the t-test motivation and conclusion

THEN

Person B codes the next bit which is a confidence interval.
Person A annotates to include the CI motivation and conclusion

What do you think?   Do you have ideas for how you'd use it in class?  I just think that the information will go farther in people's minds if they have a few ideas for how it might be relevant to their data science class.

**Comment by nicholasjhorton** [comment]
I love the suggestions and have incorporated them.  If you have a minute to do an additional read I'd be most appreciative.

**Comment by hardin47** [comment]
great!  i made one tiny typo correction.

**Comment by nicholasjhorton** [comment]
ready for @hglanz final review
