### ISSUE TITLE
rstudio cloud

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#42]

**Comment by hardin47** [comment]
@nicholasjhorton did you see that Mine's RStudio talk from a few weeks ago just got posted:  https://resources.rstudio.com/webinars/rstudio-cloud-in-the-classroom

**Comment by nicholasjhorton** [comment]
Thanks for the pointer: I've drafted this and would welcome comments.

**Comment by hardin47** [comment]
did a little bit of editing (https://github.com/hglanz/DS-Blog-Ex/commit/68ad30bfac8bd229f24dd38e19914d080e7c7dbf) 

i also added a picture from Mine's talk that I really like.  i wasn't quite sure about the path to the picture, hopefully i did it right.  

i pushed but didn't rebuild.
