### ISSUE TITLE
teaching data viz

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#43]

**Comment by hardin47** [comment]
draft done!  images in the right place!  understanding of image path issues complete!  #successfulsaturdaynight

@nicholasjhorton @hglanz would love your comments on the draft.

**Comment by nicholasjhorton** [comment]
Added a pointer to Nolan and Temple Lang (https://github.com/hglanz/DS-Blog-Ex/commit/0566d3d62726b688c6e63309e564dda36729e812) and minor tweaks.  Looks great!

**Comment by hardin47** [comment]
thanks @nicholasjhorton !  great comments.

one question:  do we need the link to Nolan & Perrett twice?  Should one of the links be to Nolan and Temple Lang?  which one?

**Comment by nicholasjhorton** [comment]
I like having the Nolan and Perrett referenced twice (once as a bullet and once as a Learn More).  You could certainly add Nolan and Temple Lang but it doesn't focus as directly on viz.  I wonder whether a shoutout to one of Amelia's papers on software for teaching statistics would make sense?  https://arxiv.org/pdf/1610.00985.pdf

BTW, this could easily form the basis for a blog entry if we are looking for one.

**Comment by hardin47** [comment]
Ok, it's just that your GitHub comment said Nolan and Temple Lang.  maybe that was a typo.  And sure, i'll add Amelia's paper.

**Comment by nicholasjhorton** [comment]
sorry for my confusion.  (Just FYI I made a comment on Disqus for infer: please let me know if you see any issues)

**Comment by hardin47** [comment]
all good on infer comment.  maybe eventually i'll get a student to do that for ISCAM !!
