### ISSUE TITLE
data science for good

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#44]

**Comment by nicholasjhorton** [comment]
see http://sites.nationalacademies.org/DEPS/BMSA/DEPS_189279
and https://blog.massmutual.com/post/data-days-good

**Comment by hardin47** [comment]
just wrote a draft of data 4 good.  would love any comments from @nicholasjhorton or @hglanz.  Thanks!

**Comment by nicholasjhorton** [comment]
Added some small comments and minor corrections: looks great!  see https://github.com/hglanz/DS-Blog-Ex/commit/0566d3d62726b688c6e63309e564dda36729e812

**Comment by hardin47** [comment]
@hglanz   the first set of sub-bullet points isn't formatted correctly.  can you make sure that works when this blog gets posted to the full site?

**Comment by nicholasjhorton** [comment]
ready to close once @hglanz reviews how things look on the deployed site.
