### ISSUE TITLE
PCMI and ASA undergrad guidelines

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#46]
Can you please add a link to https://www.tandfonline.com/doi/full/10.1080/00031305.2015.1094283

**Comment by hardin47** [comment]
@nicholasjhorton @hglanz 

I wrote a draft of the curriculum guidelines blog!  I didn't build (too tired to try to get that working...).  Hopefully you can give feedback from the .Rmd or else it'll magically build when someone else is working on it.  Looking forward to your thoughts.

**Comment by nicholasjhorton** [comment]
This is good.  My main suggestion would be to note that the NASEM report and blog entry took both of those documents and expanded them.  NASEM had the explicit goal of being useful to those creating programs (and at more than 100 pages provides more details than PCMI).

Besides trying to weave the NASEM, I wonder if there are ways to highlight some specific aspects of the reports.  (I suspect that we may brainstorm in some useful ways in a few minutes.)

**Comment by hardin47** [comment]
i made edits here:  https://github.com/hglanz/DS-Blog-Ex/commit/89a08045d9cee7057e6b4c4599f53ebb238ceaa5

would love it if you looked at what i wrote to make sure that i included nasem in the way you expected.

i guess i didn't add much about other highlights.  did we talk about that?  i just added a paragraph highlighting the ability to jump start.

**Comment by nicholasjhorton** [comment]
Looks great!
