### ISSUE TITLE
Google and RStudio R style guides

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#47]
Perhaps also mention https://rpruim.github.io/Kruschke-Notes/some-useful-bits-of-r.html#style-guide?

**Comment by hglanz** [comment]
@nicholasjhorton @hardin47 draft is up on the staging site for review :)

**Comment by nicholasjhorton** [comment]
This is looking great.  The main thing I'd propose adding is a paragraph on bringing the style guides into the classroom.  I've done this in my intro to data science course by assigning each group of two students a section of the Google R Style guide.  Their job is to prepare a one minute lightning talk describing the rule and why it is important.  Some of these are easy, some are hard, but I found it helpful to engage students in taking this on.

I can imagine an exam question where they would be given a rule and asked to provide an example that violated it (and why that would be bad).

**Comment by hardin47** [comment]
@hglanz i added a few links here:  https://github.com/hglanz/DS-Blog-Ex/commit/8cf4cf9e9ef9eb6a0ddf3e2e6c447f4b3ba98a48

i also really like @nicholasjhorton 's ideas for class assignments!  the exam question is great.  (but i didn't add anything pedagogical in my edits.)

**Comment by nicholasjhorton** [comment]
I have two remaining suggestions:

I’d propose an additional sentence noting that style guides are often arbitrary but that they reinforce practices that improve readability. This point is sort of made but could be reinforced. 

Might you add a mention of the styler package and how this might be used to grade student submissions to help reinforce the practice of coding standards in a data science course?  I’m planning to do this this fall.  

All the best,

Nick

**Comment by hglanz** [comment]
I believe I've addressed all of the lingering comments. Thanks again @hardin47 for your adds.

In particular the last couple sentences of the post are now:

At the end of the day, style guides can seem arbitrary but they reinforce practices that improve readability. Good coding style and improved readability are just good computing hygiene that everyone should live by.

thanks @nicholasjhorton :)
