### ISSUE TITLE
learnr

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#48]
Have either of you used any grader or checking packages with learnr?

**Comment by hglanz** [comment]
I have not, but Kelly, my wife, and I plan to have this figured out by Fall of this year for use in our Fall classes....so theoretically we could have something to contribute to this post....

**Comment by nicholasjhorton** [comment]
Are you willing to take the learnr entry on?  

There are some nice examples that can be referenced at:

learnr::run_tutorial("introduction", package = "ggformula")

https://github.com/ProjectMOSAIC/ggformula/tree/master/inst/tutorials/introduction

**Comment by hglanz** [comment]
@nicholasjhorton @hardin47 draft is up on the staging site for review :) This one's a bit short right now, but the two tutorials that I'm linking to seem VERY good....so I wasn't sure how much to repeat in the blog post

**Comment by hardin47** [comment]
i added a bit to `learnr`.  i was trying to find a `learnr` example in the wild that connected to a previous blog entry.  couldn't find anything on `infer` or `mosaic`, but danny kaplan does have one that is sort of for `dplyr` in the statprep stuff.  feel free to change it if you find something better.

most of my edits are here:  https://github.com/hglanz/DS-Blog-Ex/commit/6bce0e51c70bb7836fae332d667a0af053a5f9c2.  but then I found some typos and messed with the formatting a little bit in later commits.

i did build, so my final version is the one on the staging site:  https://pensive-bartik-e3e658.netlify.com/learnr/

**Comment by nicholasjhorton** [comment]
I like how this is shaping up.  Some specific comments:

1. intro is too gee whiz: drop the "!" and "fantastic".  Acknowledging Garrett's work is good, but you can summarize what learnr does.

2. How about a sentence after the second sentence giving some ideas for how instructors can offer interactive tools to their students to allow them to explore datasets in use from the class and textbook (and more)?

3. Don't you need an RSConnect Server Pro to host tutorials?

4. For RStudio hosting can you be more specific (shinyapps.io?)

5. Can you describe how a user can install learnr then create a template on their own computer?

**Comment by hardin47** [comment]
i added the paragraph talking about hosting, and i wasn't really sure what hosting a shiny app means.  so @hglanz , please fix what i wrote so that it is accurate!  this connects to #3 and #4 above from @nicholasjhorton.  and maybe also work in #5 above to that same conversation?

**Comment by nicholasjhorton** [comment]
I’m still not happy with the first sentence (“well first off it’s a game changer”). I don’t think this technology is a game changer. It’s a valuable tool for instructors. 

All the best,

Nick

**Comment by nicholasjhorton** [comment]
I had one other suggestion: could you note a challenge for instructors is that students tend to blaze through tutorials and that instructors need to ensure that students know that they are responsible for what is covered (e.g., tutorial quiz low stakes on a regular basis?)

All the best,

Nick

**Comment by hglanz** [comment]
Thanks so much @hardin47 . I've removed the first sentence and addressed the other comments. To my knowledge, an RSConnect Server Pro is not required to host these. They can be hosted in a very similar way to shiny, I believe. In any case, I like what Jo added.

**Comment by nicholasjhorton** [comment]
I added two bullets at the end (on the production site): https://github.com/hglanz/teachdatascience_blog/commit/2ac29e7c2117cf5fee69d67c96d15bb5222f42bf

**Comment by hardin47** [comment]
so he's cool with us posting that?  if so, i was going to work those examples / source code / etc. into the earlier part of the blog.  do you want me to do that?

**Comment by nicholasjhorton** [comment]
Randy is good with the posting. If you feel up to integrating them (on the production site) please feel free to do so. 

All the best,

Nick

**Comment by hardin47** [comment]
ok, i did it here:  https://github.com/hglanz/teachdatascience_blog/commit/af215f48c912821b6ad499a5fd662f3668a01a40

i pushed the changes, but i didn't rebuild.  you'll do that tonight for `learnr` more generally, right?  i think i got all the images right, but it is worth a careful look to make sure nothing broke when i added the words about his tutorial.

thanks!!

**Comment by nicholasjhorton** [comment]
I made two additional changes: https://github.com/hglanz/teachdatascience_blog/commit/2537d6c051db6606ea00ca0f354589f8f8cca2ff

Please let me know if you see any issues as I'm planning to publish and double check how things look.
