### ISSUE TITLE
p-values galore (TAS special issue)

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#49]
Just FYI, I assigned these papers for my theoretical statistics students to present: I'd be glad to share that experience and assignment if useful.

**Comment by hglanz** [comment]
I would love this! Our department wanted to have a discussion of sorts, but we got busy with too many other things for it to happen yet.

**Comment by hardin47** [comment]
@hglanz 

i put half a draft of the p-value blog up.  @nicholasjhorton , i don't think you ever sent us what you do with your class on this front, did you?  do you want me to cite it?  or just crib it?  i put an assignment in that i've used in an applied class (post intro).  but i'd be happy to swap out for yours, add yours, or just generalize mine to make our suggestions more general.

i'll finish up the p-value blog in the morning, but i did just push the entry in case either of you are awake and hoping to spend the evening editing blogs.  enjoy!

**Comment by hardin47** [comment]
alright!  @hglanz and @nicholasjhorton you are up.  p-values and PCMI entries are complete.  i look forward to comments and edits. 

n.b., writing blogs is definitely a big time commitment.  however, after i've written an entry, i am always super excited about having written it and getting that idea out to the larger community.  thanks for pushing me in great ways.

**Comment by nicholasjhorton** [comment]
I like it!  My main suggestion would be to add in a mention of the ATOM proposal from the JSE special issue editorial.

**Comment by hardin47** [comment]
is this better?  https://github.com/hglanz/DS-Blog-Ex/commit/a5679095eb3a88acc34473608b624754cefaa697

**Comment by nicholasjhorton** [comment]
Looks great!

**Comment by nicholasjhorton** [comment]
Is it worthwhile adding a pointer to Andy's blog on the topic?  http://www.datadreaming.org/post/what-to-do-about-p-values/

**Comment by hardin47** [comment]
thanks for the pointer, @nicholasjhorton !  i added zieffler to the p-value blog (just in learn more, I didn't talk about details, might have done more if it wasn't going live tomorrow).

i think it'll happily rebuild tonight / tomorrow, right?
