### ISSUE TITLE
outreach to broader community

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#5]
I'm glad to do any or all of the following:

- Two Year College initiatives and lists [Nick] DONE
- isostat [Jo] DONE
- Stat Ed section [Jo] DONE
- TSHS section [Jo] DONE
- Statistical Computing Section [Nick] DONE
- Statistical Programmers Section [Nick] DONE
- Statistical Learning and Data Science Section [Nick] DONE
- ASA Community [Jo] DONE (to "ASA Connect " ... is that the same?). DONE
- MAA SIGMAA-StatEd [Jo] DONE  
- **AP Statistics list [Hunter]**
- RStudio Education Community [Jo] DONE
- Canadian Stat Group [Nick]. DONE
- Caucus Academic Representatives [Nick] DONE
- AAAS Statistics group [Nick] DONE

Do either or both of you want to put your names by lists that you would like to share the announcement with?  

I'll work on stubbing that out (pulling from the opening/motivational entry).

**Comment by hglanz** [comment]
I feel capable of doing the AP Statistics list, but otherwise I think either of you are better for the rest.

**Comment by nicholasjhorton** [comment]
I've updated the list and put my name besides a number of the outlets.

**Comment by hardin47** [comment]
i don't see your name next to the outlets.  am i missing something?

I'm happy to send it out to about half of those, but i certainly don't feel an obligation to do so.  i agree with hunter that you are probably a better emissary.  

i'll definitely tweet about it.  :)

**Comment by nicholasjhorton** [comment]
I've added myself.
