### ISSUE TITLE
PeerJ collection

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#50]

**Comment by nicholasjhorton** [comment]
I've completed my first draft and would welcome feedback.  (Note that this is now slated for next week...)

**Comment by hardin47** [comment]
i made some light edits.  i pushed here: https://github.com/hglanz/DS-Blog-Ex/commit/6a4a0234f027b0c23a5aa8b30ac17be8ad05def8

but i didn't recompile.

**Comment by hglanz** [comment]
I love this post. I have not made any changes myself.
