### ISSUE TITLE
add info on signing up for daily emails on the main blog page

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#51]
@hglanz might you be willing to add this:

Sign up for emails at https://groups.google.com/forum/#!forum/teach-data-science (you must be logged into Google to sign up).

**Comment by hglanz** [comment]
Yes! I'll do this and close the issue when I do.

**Comment by hardin47** [comment]
@hglanz 

hunter ... i was reading through the issues just to make sure i hadn't missed anything and saw this particular issue.  might be good to add the link on the new blog.  although now that i'm looking at the formatting, i'm not really sure where it will go???

**Comment by nicholasjhorton** [comment]
let's not worry about this.
