### ISSUE TITLE
blog entry on reproducibility report?

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#52]
http://www8.nationalacademies.org/onpinews/newsitem.aspx?RecordID=25303

**Comment by nicholasjhorton** [comment]
@hglanz are you willing to consider this?

**Comment by hglanz** [comment]
Yes, I would love to do this. My question is where do you think it should land timeline-wise? Reproducibility is such a common topic throughout our blog already.

**Comment by nicholasjhorton** [comment]
How about Wednesday, July 10th?

**Comment by nicholasjhorton** [comment]
Still on the list for possible entries for the future...
