### ISSUE TITLE
40,000 foot checkin on coverage of key topics

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#54]
can we schedule a conversation once @hglanz is back?

**Comment by hglanz** [comment]
I return on 6/18. I'm pretty free after that.

**Comment by hardin47** [comment]
@hglanz @nicholasjhorton  

How about 6/19 1:30pm PST, 4:30pm EST?  I'm going to pencil it in.

**Comment by nicholasjhorton** [comment]
Alas I'll be on my way to Seattle and unavailable then.  But I'd encourage you to meet without me.

**Comment by nicholasjhorton** [comment]
Things to think about coverage for summer (and beyond):
confounding and causal inference
predictive analytics vs. regression model
data analysis workflow
scaffolding projects
grading rubrics

**Comment by hardin47** [comment]
Hunter, can you meet on 6/18 at all?  Nick, what is your timing that day?

Jo Hardin
Pomona College
jo.hardin@Pomona.edu<mailto:jo.hardin@Pomona.edu>

On Jun 14, 2019, at 10:27 AM, Nicholas Horton <notifications@github.com<mailto:notifications@github.com>> wrote:


Alas I'll be on my way to Seattle and unavailable then. But I'd encourage you to meet without me.

**Comment by nicholasjhorton** [comment]
I'll try to join if I can (but I'm traveling that day as well).

**Comment by hardin47** [comment]
or you could send some times next week when you ARE available?

**Comment by nicholasjhorton** [comment]
I'm really sorry that my schedule is so constrained (or more accurately, up in the air). 

How about 8:00am PDT on Friday, June 21st?

Nick


On Jun 14, 2019, at 9:50 PM, Jo Hardin <notifications@github.com> wrote:

or you could send some times next week when you ARE available?

**Comment by hardin47** [comment]
that time works well for me.  i've penciled it in.  @hglanz ?

**Comment by hglanz** [comment]
Yes, I can do 8am PDT on 6/21.

**Comment by nicholasjhorton** [comment]
I've sent a Zoom link under separate cover.
