### ISSUE TITLE
Jenny Bryan refactoring talk UseR

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#57]
https://github.com/jennybc/code-smells-and-feels

**Comment by nicholasjhorton** [comment]
I have a draft ready for review by @hardin47 and @hglanz (upon his return from camping): https://pensive-bartik-e3e658.netlify.com/refactoring/

comments and suggestions welcomed

**Comment by hardin47** [comment]
some small comments here: https://github.com/hglanz/DS-Blog-Ex/commit/6df666bef84c9e8817fddeee788c30f8f52e8332

* i probably wouldn't use "for fun and profit" again (already said that about github)
* you said that you already encouraged the reader to watch her talk.  did you mean to point to the useR blog entry?   i didn't change, but that change should be made.

i'm good to go with those two small changes!

**Comment by hglanz** [comment]
This looks pretty good, and maybe it's just me...but did you mean to say "teaching code refactoring" at the end of the first paragraph? It feels like a weird transition from that sentence to the wikipedia definition of code refactoring.

Other than that, I'm good to go on this.

**Comment by nicholasjhorton** [comment]
Here are my changes: https://github.com/hglanz/DS-Blog-Ex/commit/8e2e6e10c5f9826baeb68785f8c4bb035be9b4c3

I fixed the first paragraph and updated the title.  I don't think it makes sense to add the UseR ref in the future (though we can always add this in later).
