### ISSUE TITLE
signup to receive notifications of the blog

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#6]
Is there an automatic mechanism for people to sign up to receive updates about new blog posts?

**Comment by hglanz** [comment]
There's the RSS....? Otherwise I'm not sure. Perhaps our intro post should also include our intended schedule of posts....not the topics necessarily, but the plan to post 5 times per week for 8 weeks or so.

**Comment by nicholasjhorton** [comment]
What about creating a google email list that will have a (manually sent) daily update?

**Comment by hglanz** [comment]
Yes, I think we could definitely do this!....though I only have cursory experience with HOW to do this.

**Comment by nicholasjhorton** [comment]
@hardin47 can you please try to sign up without an invite?  I'm hoping that if you are signed into to Google and open:

https://groups.google.com/forum/#!forum/teach-data-science

You'll see a button to join.

**Comment by hglanz** [comment]
This has been added to the Intro post and About page. @hardin47 should close this once you've signed up without an invite per @nicholasjhorton 's previous comment.

**Comment by nicholasjhorton** [comment]
@hardin47 I fixed the settings: can you try to add yourself using the 

https://groups.google.com/forum/#!forum/teach-data-science

link (when you are logged into google)?

**Comment by hardin47** [comment]
I think I signed up.  You have to let me in, right?
