### ISSUE TITLE
CODAP guest entry

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#64]

**Comment by nicholasjhorton** [comment]
@hglanz can you please take a look at the CODAP guest entry and see what's required to get the acs*.html files to be displayed when the site is built?  (In addition, a review of the draft entry would be appreciated).

@hardin47 can you please wait until the links work?

**Comment by nicholasjhorton** [comment]
@hglanz thanks for building this: the links work!  Can the two of you please take a look, kick the tires, and let me know what you think?

**Comment by nicholasjhorton** [comment]
https://pensive-bartik-e3e658.netlify.com/codap/

**Comment by hardin47** [comment]
* i think bill & tim need a slightly longer introduction.  maybe just affiliations?  kelly wrote a paragraph about her background??  [i just realized that it's at the bottom.  should we move to the top to be consistent with Kelly's blog?]

* I made some edits here:  https://github.com/hglanz/DS-Blog-Ex/commit/f7a6af633ad840c5dd43c923729c3095b049a836

* i don't understand this example:

>You might argue that the median comparison across sex is still unfair. More women than men---even women with graduate degrees---work in the home and do not have traditional incomes. 
That drags down the graduate women's median income and makes it look as if women _with jobs_ get paid less
than men, when in fact (one could claim) the incomes are really the same.

> Do you think that might be true? Let's find out using data. 

when they say "do you think that might be true?" what do you think "that" is?  can the last sentence be rewritten to exclude the word "that"?

**Comment by nicholasjhorton** [comment]
Thanks as always for your careful read and edits.

I added affiliations at the top.

Would changing "Do you think that might" to "Do you think that assertion might?" address your concern?

**Comment by hardin47** [comment]
I don't know what the assertion is.  seems like a lot of things in the paragraph.  which part is the assertion?

**Comment by nicholasjhorton** [comment]
I've looped in Tim and Bill via email.

**Comment by nicholasjhorton** [comment]
Integrated suggestions (see https://github.com/hglanz/DS-Blog-Ex/commit/c89f287a43fbbdac6b4d786ae32016a0238244eb)
