### ISSUE TITLE
Jupyter and JupyterHub

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#65]
include a brief mention of Julia?  https://www.crcpress.com/Data-Science-with-Julia/McNicholas-Tait/p/book/9781138499980

**Comment by hardin47** [comment]
@hglanz I saw this on some tweet.  not sure if you want to integrate it into the blog or maybe just put it in "learn more"?  seemed fun to me ...


https://blog.jupyter.org/99-ways-to-extend-the-jupyter-ecosystem-11e5dab7c54

**Comment by hglanz** [comment]
draft is up on the staging site for review by @nicholasjhorton and @hardin47 . Thanks!

**Comment by nicholasjhorton** [comment]
I made some light edits (see https://github.com/hglanz/DS-Blog-Ex/commit/118a756fea8d1e966ea53f32500d279a9b2871b8)

Would this be a useful additional ref?

https://data.berkeley.edu/news/jupyterhub-journey-starting-small-and-scaling

Would it make sense to note the analogies to server setup by mentioning our server entry?

**Comment by hardin47** [comment]
i made some edits and added an intro paragraph (and Nick's link):  https://github.com/hglanz/DS-Blog-Ex/commit/526bc154b135139b6b02d0c0a186f2efda9dbf12

**Comment by hglanz** [comment]
Thanks so much for this. Looks great!

**Comment by nicholasjhorton** [comment]
I concur!

**Comment by hardin47** [comment]
yes, really great entry @hglanz, thank you!!
