### ISSUE TITLE
reticulate entry

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#66]

**Comment by hardin47** [comment]
i pushed a very sparse draft of the reticulate entry.  it is not meant for comments yet.  however, the reason i pushed it is to see what type of build problems we will run into.  @hglanz , if you build the site, can you let me know whether the reticulate entry gives you any trouble?  the .Rmd file knits perfectly on my computer, but i don't know how it will go on the main site.

meanwhile, if @hglanz has any ideas on the set of data wrangling commands that we should use for the two side-by-side entries (reticulate & pandas), i'm happy for suggestions!  seemed like the flights dataset was a good one to use.  but i'm happy to use whatever.

**Comment by hglanz** [comment]
@hardin47 the entry did give me issues, but once I changed the path to point to MY python binary everything worked fine :) the draft should be built into the staging site right now.

pandas is almost like a bit of base R and dplyr for python, so mimicking a bit of what we've done in some past posts for wrangling might be a good way to go. The flights dataset sounds good to me. Titanic is a good pick too. 

A quick google search yielded:

https://towardsdatascience.com/a-quick-introduction-to-the-pandas-python-library-f1b678f34673

http://datacamp-community-prod.s3.amazonaws.com/dbed353d-2757-4617-8206-8767ab379ab3

DataCamp stuff aside, these seem like good frames of reference for our examples and post content. What do you think?

**Comment by nicholasjhorton** [comment]
What about replicating the example from the GAISE blog entry?

Nick


On Jul 4, 2019, at 2:06 AM, Hunter Glanz <notifications@github.com> wrote:

pandas is almost like a bit of base R and dplyr for python, so mimicking a bit of what we've done in some past posts for wrangling might be a good way to go. The flights dataset sounds good to me. Titanic is a good pick too.

**Comment by nicholasjhorton** [comment]
The current version (obviously) won't compile for me as it has a hardcode location:

Error in use_python("C:/Users/Hunter/Anaconda3", required = TRUE) : 
  Specified version of python 'C:/Users/Hunter/Anaconda3' does not exist.


Can we not just set things up on our machines so that we have the correct default python installed?


https://rstudio.github.io/reticulate/

Python version

By default, reticulate uses the version of Python found on your PATH (i.e. Sys.which("python")).

The use_python() function enables you to specify an alternate version, for example:

library(reticulate)
use_python("/usr/local/bin/python")
The use_virtualenv() and use_condaenv() functions enable you to specify versions of Python in virtual or Conda environments, for example:

library(reticulate)
use_virtualenv("myenv")

**Comment by hardin47** [comment]
i think we fixed the path issue (@hglanz, let me know if it doesn't work for you).

i'm waiting to see if @hglanz has a pandas entry that can / will match the reticulate entry.  if he is good to go, i'll add in all the words.  but the words part should go reasonably quickly.

@nicholasjhorton -- we decided to stick with the flights to do a little more wrangling.  also, i think the flights dataset is a good one for people to have seen!

**Comment by nicholasjhorton** [comment]
I like how this is shaping up.  Two suggestions:

1. can some pedagogical advice be added to this and/or the jupyter entry?  I'm thinking that for intro data science students it might be preferable to stick with one environment.  But more advanced students would benefit from depth in one environment (e.g., R or Python) as well as exposure to a second (python or R).  Similarly for Jupyter and RStudio.
2. The plot is kind of ugly and not so informative.  Can a third variable be included that shows some signal?  Alpha transparency changed?  Actually the more I look at it the less I like it (boxplots or violinplots would be preferable but don't really get people excited)

**Comment by hardin47** [comment]
i love both ideas.  i'll implement this afternoon.

**Comment by hardin47** [comment]
i updated the reticulate entry.

@nicholasjhorton do you have any thoughts on which should come first:  pandas or reticulate?  which ever way, we plan to reference the other.  thanks!

**Comment by nicholasjhorton** [comment]
I like the changes!

My preference would be pandas first, then pandas in R using reticulate.

Much of the introductory paragraph (Python vs. R) might want to be in both entries.

**Comment by hardin47** [comment]
ok, i rebuilt and did some wonky things.  two things that did not work for me this time around:

1. I can't get the path-free python to work (I had to add my specific path).

2. I can't get the code to show up, be evaluated, but not print the output.  So I used a workaround.  I put the first chunk in twice.  The first time tells it to print the code but not evaluate.  The second time tells it to evaluate but not print anything.  

I'd love slick-er solutions to both problems.  thanks @hglanz and @nicholasjhorton

**Comment by hardin47** [comment]
i added a link from reticulate to pandas.  @hglanz , you probably want to take out the link to "Jo's entry" on reticulate (because that would come second).

**Comment by hglanz** [comment]
Link removed :)

**Comment by nicholasjhorton** [comment]
I think that this is looking great.  The redundancy with the extra copies of the chunks is a little jarring.  (And I'd prefer to only have the ggplot output appear once).

**Comment by hardin47** [comment]
i hear you, i hear you.  i agree that it is jarring and that the ggplot seems odd twice.  HOWEVER, I know that when i try to do something new, I really really really appreciate seeing the code behind the scenes.  the whole py$flights part.  and ```{python} ...  which means i disagree with simplifying (but i did add some words saying why we've included them repeatedly).  

i'm not going to die on this hill either, and i'll simplify the post if you really think i should.

**Comment by hardin47** [comment]
@hglanz -- last remaining issue for reticulate entry is the path for python.  i'd really like you to remove the two lines of code pointing to the python engine on our local computers.  but my computer won't build with the independent path:  `use_python("/usr/local/bin/python", required = TRUE)`

does your computer build with that path?

****  IMPORTANT:  also, there are those **TWO** chunks.  one which shows code, one which runs code.  and they should probably be consistent, but i suppose they don't have to be.

do we need to talk off line about the situation?  i totally trust you to figure this out, but i'm happy to be a sounding board if we should work through this together.  thank you!!!

**Comment by nicholasjhorton** [comment]
If it's possible for @hglanz to rebuild the pensive* site I'd be glad to review.

No need for anyone to die on a hill.  I don't have strong feelings.  Thanks as always to you two for your efforts.

**Comment by hglanz** [comment]
I've rebuilt and re-pushed the staging site. I'm going to copy posts over to the real site one day at a time; so just let me know when we're good to go on this one :)

**Comment by nicholasjhorton** [comment]
The duplication here feels awkward: do both chunks need to be displayed?
<img width="896" alt="Screen Shot 2019-07-15 at 8 32 54 AM" src="https://user-images.githubusercontent.com/530542/61216406-45c38180-a6db-11e9-8738-470b8bf7c51c.png">

**Comment by hardin47** [comment]
@hglanz  sorry to keep going back and forth on this, but the remaining issue with reticulate has to do with the path.  i've tried to outline the problem above (4 back and also 9 back).  

can you build the reticulate entry without a local path?

**Comment by hardin47** [comment]
@nicholasjhorton ...  uh ... not sure where to go with the replication.  i thought the issue was already resolved.  

since you and i have different views on this, you are going to have to give me more specifics.  that is, my take is to leave them all.  if you want some removed, you have to tell me which ones to remove.  are you indicating that you want all the replicates removed?  or you only want the pandas double chunk code removed?  or am i missing something?

**Comment by nicholasjhorton** [comment]
1) What's different between the two chunks I included in the screen shot?  Isn't it clear that the second one is what is run in python?  

2) I'd still prefer to have "eval = FALSE" on the last R in R replication of the identical wrangling and ggplot.  That would include the code but not repeat the figure.

Neither of these is a big deal to me.

**Comment by hardin47** [comment]
i think it's not clear that the code is in python if you aren't an expert coder in R and/or Python.  that is, if you are a student.  base R uses a lot of square brackets.  might just be non-standard evaluation.  so i left it in.

i did make eval=FALSE in the plot, though. 

thanks for your continued diligent reads of the blog entries!!

**Comment by hglanz** [comment]
Unfortunately I have not been able to get it to work without a local path. Right now my plan is to just use my path for the real site and remove the others. I'll leave our staging site file the way it is. Sorry!

**Comment by nicholasjhorton** [comment]
Sounds good. I’m really pleased with the entry. 

All the best,

Nick

**Comment by hardin47** [comment]
ok, great.  thanks for the update.  so you'll remove my path from both of them on the live site?  i appreciate all the help!!
