### ISSUE TITLE
data8

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#68]
+ AP CS Principles plug?

**Comment by nicholasjhorton** [comment]
I've finished a first draft: comments and suggestions welcomed.  See https://github.com/hglanz/DS-Blog-Ex/commit/c9e2856124ac5c08ef78568437281af405c3b518

**Comment by hardin47** [comment]
great entry @nicholasjhorton !

some thoughts...

1.
> The creators have developed a simplified interface to Python to reduce the cognitive load of standard packages such as pandas (see a parallel in R in our “Less Volume, More Creativity” entry). They write:

* I have two comments.  (1) i'd link to the pandas entry.  (2) i'd explain a little more what you mean by parallel.  it isn't really the same thing  (tbh, it's more like CODAP if you want to talk about interface).  but i do like the comparison in the sense of lowering barriers to entry.  i'd just make the parenthetical a little more descriptive.

WAIT...  maybe it is like mosaic.  but then maybe i don't like the word "interface"  (I thought you were referring to Jupyter)...

2.  can you point out the free resources more explicitly?  you give a link to the bootstrap example, but it seems like you could write a few sentences about textbook-like-website that anyone can use.

3.  similar to #2 above (maybe this is in the same paragraph???), i think it would be nice to give a sense of what topics are covered in data8.

**Comment by hglanz** [comment]
I agree with @hardin47 and then I'm good on this post!

**Comment by nicholasjhorton** [comment]
I've addressed these comments (see https://github.com/hglanz/DS-Blog-Ex/commit/93388b9abd1569b7a2b185fa8e042a3103824d35)

**Comment by nicholasjhorton** [comment]
I incorporated David Wagner's suggestions.  This is ready to copy to the main site.
