### ISSUE TITLE
review of introductory blog entry

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#7]
I took a crack at editing Jo's stub of the intro entry.  Can you please review and comment?  It would be great if we were in a position to post this on Wednesday of this week.

See https://pensive-bartik-e3e658.netlify.com/intro/

**Comment by nicholasjhorton** [comment]
- [x] Nick approval
- [  ] Jo approval
- [  ] Hunter approval

**Comment by nicholasjhorton** [comment]
Note changes (and stub for email signup) via https://github.com/hglanz/DS-Blog-Ex/commit/d9f333dc9baaa016730227b4c252728950f111c9

**Comment by nicholasjhorton** [comment]
I made some light tweaks and am ready to publish this.  @hardin47 can you please do one final review and give @hglanz the green light?

**Comment by hglanz** [comment]
I approve. @hardin47 ?

**Comment by hardin47** [comment]
looks great! 

(One small point here in the intro as well as the "about" and the outreach stuff...  do we want to note anything about 2019?  I know the blog will have a post date, but it just seems odd to me to say "this summer starting on Tuesday, May 28th." without saying 2019.)  Thoughts?

**Comment by nicholasjhorton** [comment]
Adding 2019 sounds like a good plan.

**Comment by nicholasjhorton** [comment]
Hunter, can you publish the intro entry?  It would be great to have this out before the holiday weekend.

Thanks in advance,

Nick


On May 24, 2019, at 7:22 AM, Jo Hardin <notifications@github.com> wrote:

looks great!

(One small point here in the intro as well as the "about" and the outreach stuff... do we want to note anything about 2019? I know the blog will have a post date, but it just seems odd to me to say "this summer starting on Tuesday, May 28th." without saying 2019.) Thoughts?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


Nicholas Horton 
Beitzel Professor of Technology and Society (Statistics and Data Science)
Amherst College

**Comment by hglanz** [comment]
Done and published!

**Comment by nicholasjhorton** [comment]
Thanks!

All the best,

Nick

**Comment by nicholasjhorton** [comment]
This looks great. 

Might you be willing to tweet an announcement that I can retweet?

All the best,

Nick

**Comment by hglanz** [comment]
Will do!

**Comment by hglanz** [comment]
Tweet made!

**Comment by hglanz** [comment]
Should we tweet about every new post or is that too much?
