### ISSUE TITLE
Python community

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#70]

**Comment by hardin47** [comment]
i just posted a draft of the python community.  it could definitely use some more words, but i'd love feedback on whether the links i put on are reasonable / complete.

@nicholasjhorton @hglanz do either of you know any python fanatics that could look at the blog draft and point out of i'm missing anything obvious?  or characterized something completely wrong?

**Comment by nicholasjhorton** [comment]
Some words at the beginning would be helpful.

Worth noting?  
- https://qz.com/1624252/pythons-creator-thinks-it-has-a-diversity-problem/ 
- https://fossbytes.com/python-creator-language-male-attitude-hurting-programming/
- https://revolution-computing.typepad.com/.a/6a010534b1db25970b01bb0911aa8b970d-pi


How about mentioning the Data Science Education workshop (mentioned in the Data8 entry)?  https://data.berkeley.edu/academics/resources/data-science-education-workshops/2019-national-workshop-data-science-education


Chris Fonnesbeck would be a *great* person to ask.  His email is chris.fonnesbeck@vanderbilt.edu

**Comment by hardin47** [comment]
while I personally agree that Python has a big problem attracting women, i'm hesitant to include those links in our blog.  i was trying to make the entry a really positive celebration of Python (in contrast to the rest of the entire blog which is a celebration of R).    so i'm not comfortable bringing up the gender issue in this particular blog entry.  is that short sighted of me?

i added words and the link to the workshop.  i'll send to chris fonnesbeck right now.  Thanks!

**Comment by nicholasjhorton** [comment]
I’m happy to defer to you. Staying positive sounds like a reasonable plan. 

All the best,

Nick

**Comment by nicholasjhorton** [comment]
I'm ready to close this one...
