### ISSUE TITLE
data100 (+ Computing in the Statistics and Data Science Curriculum shoutout?)

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#71]

**Comment by hardin47** [comment]
@nicholasjhorton what does "Computing in the Statistics and Data Science Curriculum shoutout" mean?

**Comment by hardin47** [comment]
week8 is upon us, and week9 isn't far behind!!  i just posted an entry for datat100, and i'd love feedback from @nicholasjhorton and @hglanz .

**Comment by nicholasjhorton** [comment]
This looks good to me: I made some light edits.

**Comment by hardin47** [comment]
@nicholasjhorton what does "Computing in the Statistics and Data Science Curriculum shoutout" mean?  did i cover what you were thinking (see the title of this particular issue) ?

**Comment by nicholasjhorton** [comment]
See https://github.com/hglanz/DS-Blog-Ex/commit/fa11f9c824f8b9d10e8def35906d8f2e822bda1d for the link that I added at the end.  If there's a place elsewhere in the entry to note that there is a call for papers for the special issue please feel free to add it.  Otherwise I'm fine with the mysterious link at the end.

**Comment by hardin47** [comment]
perfect.  right, slightly mysterious.  however, it's the right audience, and hopefully it'll get some clicks.  i think i'm done with this entry.  

@hglanz let me know if you see anything worth changing.

**Comment by nicholasjhorton** [comment]
one last request: 

would you be willing to add a note near the end: "Have thoughts on the role of computing in the statistics and data science curriculum?  Consider submitting a paper to the [special issue of JSE](http://nhorton.people.amherst.edu/JSEFlier2.pdf) devoted to this topic

Feel free to flip a fair coin if you are on the fence (or just close the issue if you think it inappropriate).

**Comment by hardin47** [comment]
done, great!

**Comment by nicholasjhorton** [comment]
perhaps mention the authors of the book (By Sam Lau, Joey Gonzalez, and Deb Nolan)?

**Comment by nicholasjhorton** [comment]
Perhaps adding a pointer to a specific activity or section (like the bootstrap link from data8)?

**Comment by hardin47** [comment]
great idea!  i added a bit on how they provide mathematical details on the bias-variance tradeoff.  what do you think?  https://github.com/hglanz/DS-Blog-Ex/commit/01a646616d61bdc9a0d12f45c3479832e5ab7d99
