### ISSUE TITLE
reprex

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#72]

**Comment by nicholasjhorton** [comment]
changing to 7/11 (and new milestone)

**Comment by nicholasjhorton** [comment]
fixed several minor typos (https://github.com/hglanz/DS-Blog-Ex/commit/42c834c2b8d91d89c1adf6d4b486fd9eda2b9cbc)

note that r-studio tag should be rstudio.  I'll also fix Hunter's style blog on the published site (but not rebuild).

Can you add a closing sentence about how you teach this (or require students to submit reprex's?)

Would it be worthwhile to add a sentence encouraging students to run their reprex's before they submit them to ensure that they are fully self-contained?

**Comment by hardin47** [comment]
thanks @nicholasjhorton !!  some final edits here: https://github.com/hglanz/DS-Blog-Ex/commit/99fa5451fce1d490f0d2a951a20f1504949e384f

* the tags really confuse me.  i always go to the live site to check.  we have 3 r-studio.  we also have 25 r-markdown.  but i suppose r-markdown vs rstudio makes sense if you think of "-" as a space.

* i don't have students use `reprex`, but i added a sentence about teaching with it.  i hope to implement  that soon!!

* i don't really know what you mean about running it before they submit it.  i mean, they sort of have to do that.  i'm not sure the use case you are worried about that gets them into trouble.  (I'm going to close this issue, but feel free to re-open if you think this particular point is important to address.)

**Comment by nicholasjhorton** [comment]
I fixed a typo.  

I have no further concerns: this looks great!

Nick


On Jul 5, 2019, at 11:18 AM, Jo Hardin <notifications@github.com> wrote:

	• i don't have students use reprex, but i added a sentence about teaching with it. i hope to implement that soon!!

	• i don't really know what you mean about running it before they submit it. i mean, they sort of have to do that. i'm not sure the use case you are worried about that gets them into trouble. (I'm going to close this issue, but feel free to re-open if you think this particular point is important to address.)


Nicholas Horton 
Beitzel Professor of Technology and Society (Statistics and Data Science)
Amherst College

**Comment by hglanz** [comment]
I believe spaces do show up as "-" in the tags.
