### ISSUE TITLE
algorithmic bias

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#74]

**Comment by hardin47** [comment]
i put up a draft of algorithmic bias.  i still need to add some links under "learn more".    but i'd love comments  from @nicholasjhorton and @hglanz

**Comment by nicholasjhorton** [comment]
This looks great.  My main suggestion would be to add some links to specifics in the first paragraph ("following the recent news").

**Comment by hardin47** [comment]
great idea, i added a bunch of links.  soooo many news articles lately!

**Comment by nicholasjhorton** [comment]
Minor changes via https://github.com/hglanz/DS-Blog-Ex/commit/034460f985847b4497bd21b91b593723127bee0a

**Comment by hardin47** [comment]
thanks for the changes!  @nicholasjhorton  made me realize that i had meant to include a bunch of curricular resources.  i've done that now with an additional section on the blog.  https://github.com/hglanz/DS-Blog-Ex/commit/5307445fa61d6a0d9d5667ea4ed49ac1b0508545

**Comment by nicholasjhorton** [comment]
Looks great.

Have you seen https://www.nitrd.gov/pubs/National-AI-RD-Strategy-2019.pdf

**Comment by hardin47** [comment]
great, i added it! thanks.
