### ISSUE TITLE
testthat

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#75]

**Comment by hglanz** [comment]
draft posted to the staging site for review by @nicholasjhorton and @hardin47

**Comment by hardin47** [comment]
took me a long time to understand the functionality of `testthat`.  do you think you can add an example to the blog?  i went to a recent meetup where the person was talking about `testthat`, all the slides and everything else are here:  
https://github.com/laRusers/presentations/tree/master/2019-06-10-unit_testing

any chance you could add an example or two?

**Comment by hardin47** [comment]
actually, i think a different example might be better.  @nicholasjhorton I remember you said something about a use case for `testthat` which was *other* than writing a function.  do you remember what it was?  originally, i thought function writing was too high level, but i remember your example felt a lot more accessible.

@hglanz do you think there is some type of example you can add to the blog so that people have some sense of what the function does?

**Comment by hglanz** [comment]
@hardin47 yes! I would love a good example! This was very much meant as a draft; everything I was coming up with seemed arbitrary and small. 

@nicholasjhorton do you have an example for testthat?!

Anything you have to suggest would be great!

**Comment by nicholasjhorton** [comment]
I've added an example: comments and suggestions welcomed.

https://github.com/hglanz/DS-Blog-Ex/commit/64b849c66e9d719aa463f3d89f86a435499932af

**Comment by hardin47** [comment]
i love the example that @nicholasjhorton added!  But I have some questions...

* why is the subsection called "regression testing"?  how is regression related to the dataset?

* why do you need the "try" part of the function?  do we really need it?  does it make the example more complicated than necessary?

* I'd love more words between each of the code lines.  for example, "when we test against the list of all countries, we do not get an error.  however, when we compare against the smaller country list of just c("Canada", "UK", "US"), the `expect_setequal` function will tell us which entries in the `country` vector are not in our smaller test set."  or something (for all the lines)

* in the current compile, the functions `expect_lt` and `expect_gt` cannot be found.  Maybe you need to use `testthat::expect_lt` and `testthat::expect_gt`?

**Comment by hglanz** [comment]
Thanks so much @nicholasjhorton for the example! I look forward to your responses to @hardin47 's questions :)

**Comment by nicholasjhorton** [comment]
Here's my updates: https://github.com/hglanz/DS-Blog-Ex/commit/ca970944b125e4646c26e8aa8322dc18eae79460

Would this be an appropriate entry to have both Hunter and I as authors?

**Comment by hardin47** [comment]
i'm still not convinced that "regression testing" is what is going on here, i looked at the wikipedia page, which says the following.  seems like what we are doing is getting a sense for the dataset in order to understand how it will be used in a forthcoming data analysis.

> Regression testing is re-running functional and non-functional tests to ensure that previously developed and tested software still performs after a change. 

but i know we are all running out of steam, so i'm definitely not going to die on this hill.

i don't think testthat was built yet.  i'd like to see that all the functions are working (they aren't working in the current build).  let's make sure they work before we sign off on testthat.

i'm totally fine with you all being co-authors.

**Comment by nicholasjhorton** [comment]
Regression testing using testthat is definitely a different use case than data consistency/validation.  The point here is that the same tools work for both.  Does that help?  Can that sentiment be added to the entry?

On Jul 14, 2019, at 12:24 PM, Jo Hardin <notifications@github.com> wrote:

i'm still not convinced that "regression testing" is what is going on here, i looked at the wikipedia page, which says the following. seems like what we are doing is getting a sense for the dataset in order to understand how it will be used in a forthcoming data analysis.

Regression testing is re-running functional and non-functional tests to ensure that previously developed and tested software still performs after a change.

but i know we are all running out of steam, so i'm definitely not going to die on this hill.

i don't think testthat was built yet. i'd like to see that all the functions are working (they aren't working in the current build). let's make sure they work before we sign off on testthat.

i'm totally fine with you all being co-authors.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


Nicholas Horton 
Beitzel Professor of Technology and Society (Statistics and Data Science)
Amherst College

**Comment by hardin47** [comment]
i suppose.  i don't find it a compelling subheading, but i don't really care one way or the other.

**Comment by nicholasjhorton** [comment]
Pointing out the subheading was helpful: it's distracting.  I changed it (see https://github.com/hglanz/DS-Blog-Ex/commit/bc36bab488994aa7deefadba51173af0a763859b)

**Comment by hglanz** [comment]
Thank you both so much for your efforts on this. I am quite glad to add @nicholasjhorton as an author to the entry :)
