### ISSUE TITLE
finalize plans for week 10

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#76]
Here's the current list:

1. We need a volunteer for the Cloud computing entry.  (I'd be glad to do this if someone else wanted the Statistics at Google Scale"
2. We need an entry for Thursday
3. We need to put our thoughts together for the closing sermon

Week of July 29th: JSM week! Peering into the future

Monday 7/29 XX XX (XX)	[likely Amelia?]
Tuesday 7/30 Teaching Statistics at Google Scale (Nick)
Wednesday 7/31 moving to Cloud computing/AWS/GCP/Azure + teaching credits (XX) [cite NSF workshop report]
Thursday 8/1 Closing thoughts (All)
Friday 8/2 - well deserved break

**Comment by nicholasjhorton** [comment]
What about a blog post on the idea that all tests are linear models?

https://lindeloev.github.io/tests-as-linear/

I also merged the Google Scale/Cloud entry (which leaves us with space for two more entries)

**Comment by hardin47** [comment]
i don't really want to write an entry on google scale / cloud computing.   i'll think about what could go on that tuesday.  have you heard from amelia at all about her post?  

i can also draft a closing thoughts entry.  i'll do that sometime in the next week.

**Comment by hardin47** [comment]
what about an entry on modeling in general.  some things that could go into it:

* all models are linear
* variance-bias tradeoff
* model for model's sake (i.e., statistics) vs. model for prediction sake (i.e., machine learning)
* causal inference
* trees:  http://www.r2d3.us/visual-intro-to-machine-learning-part-1/

**Comment by nicholasjhorton** [comment]
Here's my proposal for week 10: I'm not wedded to anything besides @hardin47's excellent closing thoughts and a hope that we might take Friday off...

- [ ] Monday 7/29 Counting commits (Amelia)
- [ ] Tuesday 7/30 Common tests are linear models + confounding (Nick)
- [ ] Wednesday 7/31 moving to Cloud computing/AWS/GCP/Azure + teaching credits (Nick) 
- [ ] Thursday 8/1 Closing thoughts (All)
- [ ] Friday 8/2 - well deserved break

**Comment by hardin47** [comment]
looks great to me!  i'm good to go for next week (week 9), and i'll try to get to review of week 10 entries by the end of the week.

**Comment by hardin47** [comment]
@nicholasjhorton 
- [ ] Monday 7/29 Counting commits (Amelia)
- [ ] Tuesday 7/30 Common tests are linear models + confounding (Nick)
- [ ] Wednesday 7/31 moving to Cloud computing/AWS/GCP/Azure + teaching credits (Nick) 
- [ ] Thursday 8/1 Closing thoughts (All)
- [x] Friday 8/2 - well deserved break

@hglanz 
- [ ] Monday 7/29 Counting commits (Amelia)
- [ ] Tuesday 7/30 Common tests are linear models + confounding (Nick)
- [ ] Wednesday 7/31 moving to Cloud computing/AWS/GCP/Azure + teaching credits (Nick) 
- [ ] Thursday 8/1 Closing thoughts (All)
- [x] Friday 8/2 - well deserved break

@hardin47 
- [ ] Monday 7/29 Counting commits (Amelia)
- [ ] Tuesday 7/30 Common tests are linear models + confounding (Nick)
- [ ] Wednesday 7/31 moving to Cloud computing/AWS/GCP/Azure + teaching credits (Nick) 
- [ ] Thursday 8/1 Closing thoughts (All)
- [x] Friday 8/2 - well deserved break

**Comment by hglanz** [comment]
This all looks great to me and I'm good to go for next week. The dates are bit off on the staging site, so I'm going to use the dates here as my guide for posting to the real site.

My wife and I are staying with my wife's family while here in Denver (she's from Denver), but they don't have wifi. So, my plan is to hit the closest starbucks by around 7am each day and post to the real blog then. I hope this is alright, but let me know if you'd like for this to be handled differently.

**Comment by hardin47** [comment]
no problem about the 7am posting.  thanks for your work!

**Comment by nicholasjhorton** [comment]
I concur. It’s also fine by me if you post late afternoon early evening of the previous day. 

All the best,

Nick
