### ISSUE TITLE
data package entry

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#78]
Nick has reached out to Kelly: https://github.com/mcconvil/pdxTrees

**Comment by nicholasjhorton** [comment]
now scheduled for July 23...

**Comment by nicholasjhorton** [comment]
I've added the draft that Kelly put together.  @hglanz might you be willing to do the magic to get the two png files appropriately structured in the static area?  I've just included what Kelly provided in the folder https://github.com/hglanz/DS-Blog-Ex/tree/master/content/post/2019_07_23_datapackage

**Comment by hglanz** [comment]
I changed the syntax for the image inclusion up a bit in her file. I like the way @hardin47 does it :)

The post seems to look right on the staging site now, but let me know if you want to change the dimensions of the images (or you can do it in the .Rmd file).

https://pensive-bartik-e3e658.netlify.com/datapackage/

**Comment by hardin47** [comment]
blog looks great!  nice work, team.
