### ISSUE TITLE
Passion Driven statistics

### ISSUE THREAD

**Issue by hardin47** [hglanz/DS-Blog-Ex#79]
agenda:

* final topics

**Comment by hardin47** [comment]
Hello,
 
I would like to submit the following for consideration as a guest post. If you would like it more detailed with sections like your other blog posts I am happy to do so.
 
Thank You,
Kristin
 
Here is the link to the new Passion-Driven Statistics e-book!
 
http://bit.ly/Passion-DrivenStatistics
 
Passion-Driven Statistics is an NSF-funded, multidisciplinary, project-based curriculum that supports students in conducting data-driven research, asking original questions, and communicating methods and results using the language of statistics. The curriculum supports students to work with existing data covering psychology, health, earth science, government, business, education, biology, ecology and more. From existing data, students are able to pose questions of personal interest and then use statistical software (e.g. SAS, R, Python, Stata, SPSS) to answer them. The e-book is presented in pdf format for ease of use across platforms. It can also be customized by downloading and editing the .iba file (available through the link below) using the free “iBook Author” software.
 
http://bit.ly/EditPDSe-book
 
For more information, contact Lisa Dierker, ldierker@wesleyan.edu, kristin.flaming@gmail.com or check out the Passion-Driven Statistics website at https://passiondrivenstatistics.com/

**Comment by nicholasjhorton** [comment]
can we think of a place where we can mention this approach?

**Comment by hardin47** [comment]
@nicholasjhorton what do you think about adding it to the curriculum guides?  we could maybe make a section on books that are modernizing?  what else we would include?

* lock5
* iscam
* baumer, horton, kaplan
* ISLR
* practicing statistics (kuiper)
* ????

**Comment by nicholasjhorton** [comment]
mention as part of data8 entry (to be done by @nicholasjhorton

**Comment by nicholasjhorton** [comment]
I've included this at the end of the data8 entry.  Additions welcomed.
