### ISSUE TITLE
closing thoughts entry

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#83]
Could we each offer some reflections?

**Comment by hardin47** [comment]
i wrote a draft of our LAST entry!  while it has a tiny bit of reflection on my end, it's more of a summary of what we did.  i also left our bios in (feel free to remove if that feels inappropriate).

i'm happy to have @nicholasjhorton and @hglanz add whatever you want in terms of reflection (i agree, reflection is good!), but i'm pretty excited (for my own sake) to have a complete list of all the blogs.

categories:  feel free to move the blogs around or add / remove categories.  the one thing i feel moderately strongly about is that we don't try to have 25 different categories.  i think the fewer categories, the better.  just my $0.02.

**Comment by nicholasjhorton** [comment]
I love this: thanks for drafting it.  Minor suggestions at https://github.com/hglanz/DS-Blog-Ex/commit/e7abfcab045e12baad983c822ccbf469de32efab

**Comment by nicholasjhorton** [comment]
I made some other light edits (and am closing this now).
