### ISSUE TITLE
Breiman's two cultures

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#87]
Are we still planning this?

**Comment by nicholasjhorton** [comment]
I've stubbed out a draft (https://github.com/hglanz/DS-Blog-Ex/tree/master/content/post/2019_07_24_TwoCultures): comments and suggestions welcomed.

**Comment by nicholasjhorton** [comment]
This entry didn't get created on the staging site when @hglanz pushed the last build.  Is it possible that missing packages caused it to fail compilation?

**Comment by hardin47** [comment]
i love it.  i made some edits as well as fixed up the R code so that the formatting was better.  and i added a reference & screen shot to http://www.r2d3.us/visual-intro-to-machine-learning-part-1/  (one of my very favorite resources to teach with!).

edits here: https://github.com/hglanz/DS-Blog-Ex/commit/1c1503abeea6ba9395f1041b1a0e64fb70fb3798

**Comment by hardin47** [comment]
also, i added one more package `rpart.plot`  ... @hglanz might need to install that package, too.

**Comment by nicholasjhorton** [comment]
@hglanz can you please let me know if you see any issues or have any suggestions?

**Comment by hardin47** [comment]
@nicholasjhorton what do you think about adding the package to some of the rpart commands?

`rpart.plot::rpart.plot(tree2)`

i know it feels tedious, but i am soooo incredibly appreciative when i am trying to learn something and i see those package links.  (and it'll help distinguish `rpart` and `partykit` and `rpart.plot`.)

**Comment by hardin47** [comment]
@hglanz i'm a little worried about the URL for this one ... i think it is "twocultures" in some places and "breiman" (I saw that URL in the closing) in other places.  @nicholasjhorton which link do you want?

**Comment by nicholasjhorton** [comment]
Ack.  My bad.  I'd prefer "twocultures".

Nick


> On Jul 22, 2019, at 3:22 PM, Jo Hardin <notifications@github.com> wrote:
> 
> @hglanz i'm a little worried about the URL for this one ... i think it is "twocultures" in some places and "breiman" (I saw that URL in the closing) in other places.  @nicholasjhorton which link do you want?
> 
> 

Nicholas Horton 
Beitzel Professor of Technology and Society (Statistics and Data Science)
Amherst College

**Comment by nicholasjhorton** [comment]
> On Jul 22, 2019, at 3:07 PM, Jo Hardin <notifications@github.com> wrote:
> 
> @nicholasjhorton what do you think about adding the package to some of the rpart commands?
> 
> rpart.plot::rpart.plot(tree2)
> 
> i know it feels tedious, but i am soooo incredibly appreciative when i am trying to learn something and i see those package links. (and it'll help distinguish rpart and partykit and rpart.plot.)
> 

I'm happy to make the change (and have done so).

Nick

**Comment by hardin47** [comment]
i prefer two cultures, too.  i'll fix the link in the closing, hopefully it isn't anywhere else.
