### ISSUE TITLE
duplicate entry

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#88]
The duplicate entry for the parallel post seems to have crept in again...
![Screen Shot 2019-07-18 at 9 36 44 AM](https://user-images.githubusercontent.com/530542/61461918-bbc82280-a93f-11e9-8e93-602a0188437f.png)

**Comment by hglanz** [comment]
I think this is fixed. Let's keep an eye on it though.

**Comment by nicholasjhorton** [comment]
Thanks!

All the best,

Nick
