### ISSUE TITLE
all the world is a model (plus some confounding)

### ISSUE THREAD

**Issue by nicholasjhorton** [hglanz/DS-Blog-Ex#89]
I have an idea for a week ten entry.  I'll stub it out and let you two determine if it fits.

**Comment by nicholasjhorton** [comment]
Here's a first crack at the entry.  Comments and suggestions welcomed.

https://github.com/hglanz/DS-Blog-Ex/tree/master/content/post/2019_07_30_onemodel

**Comment by nicholasjhorton** [comment]
Is it possible to make the png file a clickable link that gets you through to the pdf on the website?

Just FYI, thanks to Hunter's efforts the draft can be viewed at https://pensive-bartik-e3e658.netlify.com/onemodel/

**Comment by hardin47** [comment]
looks great.  i made a few edits here: https://github.com/hglanz/DS-Blog-Ex/commit/8ac161772f4ff939769cb4aa66b4ed9d5b6f5a43

**Comment by hardin47** [comment]
ps  @nicholasjhorton I've been using html code for all my images, and then i can easily add a figure caption with the link.  not as good as clicking the image, but at least the link and image are connected.

see the turkish language facebook post from this entry:  https://pensive-bartik-e3e658.netlify.com/algbias/

**Comment by nicholasjhorton** [comment]
I'm fine leaving things as they were (since there are links to the R and Python cheatsheets immediately afterwards).
