### ISSUE TITLE
more lingering entries

### ISSUE THREAD

**Issue by hardin47** [hglanz/DS-Blog-Ex#91]
it seems like there are still some lingering links on the live blog.  any chance we can get them to go away?  they look like they are related to the CODAP entry:

https://teachdatascience.com//page/5/

https://teachdatascience.com/acs02/

https://teachdatascience.com/acsx01/

etc.  (I think there are 4 that don't belong)

**Comment by hglanz** [comment]
Yeah, these CODAP ones have been tricky for me. I'm still working on it, sorry.
