### ISSUE TITLE
50th entry - next steps

### ISSUE THREAD

**Issue by hardin47** [hglanz/DS-Blog-Ex#92]
my thoughts on this "next steps" entry is that it would serve as a repository for things we might like the community to know about.  for example, we may end up adding to it from time to time if something comes up.  of course, any of us (read: @nicholasjhorton) may decide to add another entire entry (as opposed to a bullet point in the "next steps" entry) down the road just to share new ideas.

i'll draft the last entry, but it probably won't be before monday.  if we have the bandwidth, i think we should post it on friday.  that way, it'll sort of round out the summer.

RE: getting together.  i have time sunday night (dinner or after), monday night (after dinner), or tuesday lunch.  i leave tuesday afternoon.  does any of that work for either of @nicholasjhorton @hglanz ?

**Comment by hardin47** [comment]
https://askgoodquestions.blog/

https://nhorton.people.amherst.edu/JSEFlier2.pdf

Does the data100 course inspire thoughts on the role of computing in the statistics and data science curriculum? Consider submitting a paper to the upcoming special issue of JSE devoted to the topic.

**Comment by hglanz** [comment]
I could do

- after dinner Sunday
- after dinner Monday
- tuesday lunch

I really like the repository idea for the next steps entry and I’m happy to post it early Friday morning.

**Comment by hardin47** [comment]
here you go.  feel free to edit!  https://github.com/hglanz/DS-Blog-Ex/commit/026a89f6e244673a7de8e283aa073a876d467d2a

**Comment by nicholasjhorton** [comment]
Looks great.  Note that I added the link to the abstract submission form and moved the end of blog material to past tense (see https://github.com/hglanz/DS-Blog-Ex/commit/d80c4421d17970128fca9f0e2bbbaf384eda8a4e).  Another set of eyes would be helpful.
